openapi: 3.0.3
info:
  title: Billing API
  version: 1.0.0
  description: REST API OpenAPI documentation for the Billing API
paths:
  /billing/invoices/{period}:
    get:
      operationId: retrieveInvoice
      description: Retrieve invoice data for a specific period.
      summary: Retrieve details of an invoice
      parameters:
      - in: path
        name: period
        schema:
          type: string
          pattern: ^\d{2}-\d{4}$
        required: true
      tags:
      - Billing - Invoices
      security:
      - tokenAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: Invoice details (application/pdf)
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10001:
                  value:
                    errors:
                    - status: '401'
                      code: '10001'
                      title: Authentication Failed
                      detail: Invalid authentication credentials.
                  summary: Authentication Failed
                  description: Invalid authentication credentials.
          description: Authentication Failed
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10003:
                  value:
                    errors:
                    - status: '403'
                      code: '10003'
                      title: Permission Denied
                      detail: You do not have permission to perform this action.
                  summary: Permission Denied
                  description: You do not have permission to perform this action.
                Error-13001:
                  value:
                    errors:
                    - status: '403'
                      code: '13001'
                      title: Account Status Not Allowed To View Invoices
                      detail: You can only view invoices when your account is {allowed_statuses}
                      meta:
                        allowed_statuses:
                        - ONLINE
                        - TRIAL
                        - BLOCKED
                  summary: Account Status Not Allowed To View Invoices
                  description: You can only view invoices when your account is {allowed_statuses}
          description: Permission Denied
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10004:
                  value:
                    errors:
                    - status: '404'
                      code: '10004'
                      title: Not Found
                      detail: Not found.
                  summary: Not Found
                  description: Not found.
          description: Not Found
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-13000:
                  value:
                    errors:
                    - status: '400'
                      code: '13000'
                      title: Invoice Not Available For Future Periods
                      detail: You can only view invoices for past periods.
                  summary: Invoice Not Available For Future Periods
                  description: You can only view invoices for past periods.
          description: Bad Request
components:
  schemas:
    JSONAPIErrorObject:
      type: object
      description: Serializer for a single JSON:API error object.
      properties:
        status:
          type: string
          description: The HTTP status code applicable to this problem
          pattern: ^\d{3}$
          maxLength: 3
          minLength: 3
        code:
          type: string
          description: An application-specific error code
          pattern: ^\d{5}$
          maxLength: 5
          minLength: 5
        title:
          type: string
          description: A short, human-readable summary of the problem
          pattern: ^.*$
          maxLength: 4096
          minLength: 1
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of
            the problem
          pattern: ^.*$
          maxLength: 4096
          minLength: 1
        source:
          allOf:
          - $ref: '#/components/schemas/JSONAPIErrorSource'
          description: References to the primary source of the error
        meta:
          type: object
          additionalProperties: {}
          description: Non-standard meta-information about the error
      title: JSONAPIErrorObject
      additionalProperties: false
    JSONAPIErrorResponse:
      type: object
      description: Serializer for a JSON:API error response.
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/JSONAPIErrorObject'
          description: Array of error objects
      required:
      - errors
      title: JSONAPIErrorResponse
      additionalProperties: false
    JSONAPIErrorSource:
      type: object
      description: Serializer for the 'source' object in a JSON:API error.
      properties:
        pointer:
          type: string
          description: JSON Pointer to the value in the request document that caused
            the error
          pattern: ^(/[^/]+)+$
          maxLength: 4096
          minLength: 1
        parameter:
          type: string
          description: URI query parameter that caused the error
          pattern: ^.*$
          maxLength: 4096
          minLength: 1
        header:
          type: string
          description: Request header name that caused the error
          pattern: ^.*$
          maxLength: 4096
          minLength: 1
      title: JSONAPIErrorSource
      additionalProperties: false
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
