/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgeapi/api/openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResponseRetrieveCacheSetting type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseRetrieveCacheSetting{}

// ResponseRetrieveCacheSetting struct for ResponseRetrieveCacheSetting
type ResponseRetrieveCacheSetting struct {
	Data CacheSetting `json:"data"`
}

type _ResponseRetrieveCacheSetting ResponseRetrieveCacheSetting

// NewResponseRetrieveCacheSetting instantiates a new ResponseRetrieveCacheSetting object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseRetrieveCacheSetting(data CacheSetting) *ResponseRetrieveCacheSetting {
	this := ResponseRetrieveCacheSetting{}
	this.Data = data
	return &this
}

// NewResponseRetrieveCacheSettingWithDefaults instantiates a new ResponseRetrieveCacheSetting object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseRetrieveCacheSettingWithDefaults() *ResponseRetrieveCacheSetting {
	this := ResponseRetrieveCacheSetting{}
	return &this
}

// GetData returns the Data field value
func (o *ResponseRetrieveCacheSetting) GetData() CacheSetting {
	if o == nil {
		var ret CacheSetting
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ResponseRetrieveCacheSetting) GetDataOk() (*CacheSetting, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ResponseRetrieveCacheSetting) SetData(v CacheSetting) {
	o.Data = v
}

func (o ResponseRetrieveCacheSetting) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseRetrieveCacheSetting) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ResponseRetrieveCacheSetting) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseRetrieveCacheSetting := _ResponseRetrieveCacheSetting{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponseRetrieveCacheSetting)

	if err != nil {
		return err
	}

	*o = ResponseRetrieveCacheSetting(varResponseRetrieveCacheSetting)

	return err
}

type NullableResponseRetrieveCacheSetting struct {
	value *ResponseRetrieveCacheSetting
	isSet bool
}

func (v NullableResponseRetrieveCacheSetting) Get() *ResponseRetrieveCacheSetting {
	return v.value
}

func (v *NullableResponseRetrieveCacheSetting) Set(val *ResponseRetrieveCacheSetting) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseRetrieveCacheSetting) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseRetrieveCacheSetting) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseRetrieveCacheSetting(val *ResponseRetrieveCacheSetting) *NullableResponseRetrieveCacheSetting {
	return &NullableResponseRetrieveCacheSetting{value: val, isSet: true}
}

func (v NullableResponseRetrieveCacheSetting) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseRetrieveCacheSetting) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


