/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgeapi/api/openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResponseFirewallRuleEngine type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseFirewallRuleEngine{}

// ResponseFirewallRuleEngine struct for ResponseFirewallRuleEngine
type ResponseFirewallRuleEngine struct {
	State *string `json:"state,omitempty"`
	Data FirewallRuleEngine `json:"data"`
}

type _ResponseFirewallRuleEngine ResponseFirewallRuleEngine

// NewResponseFirewallRuleEngine instantiates a new ResponseFirewallRuleEngine object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseFirewallRuleEngine(data FirewallRuleEngine) *ResponseFirewallRuleEngine {
	this := ResponseFirewallRuleEngine{}
	this.Data = data
	return &this
}

// NewResponseFirewallRuleEngineWithDefaults instantiates a new ResponseFirewallRuleEngine object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseFirewallRuleEngineWithDefaults() *ResponseFirewallRuleEngine {
	this := ResponseFirewallRuleEngine{}
	return &this
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ResponseFirewallRuleEngine) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseFirewallRuleEngine) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ResponseFirewallRuleEngine) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *ResponseFirewallRuleEngine) SetState(v string) {
	o.State = &v
}

// GetData returns the Data field value
func (o *ResponseFirewallRuleEngine) GetData() FirewallRuleEngine {
	if o == nil {
		var ret FirewallRuleEngine
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ResponseFirewallRuleEngine) GetDataOk() (*FirewallRuleEngine, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ResponseFirewallRuleEngine) SetData(v FirewallRuleEngine) {
	o.Data = v
}

func (o ResponseFirewallRuleEngine) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseFirewallRuleEngine) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ResponseFirewallRuleEngine) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseFirewallRuleEngine := _ResponseFirewallRuleEngine{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponseFirewallRuleEngine)

	if err != nil {
		return err
	}

	*o = ResponseFirewallRuleEngine(varResponseFirewallRuleEngine)

	return err
}

type NullableResponseFirewallRuleEngine struct {
	value *ResponseFirewallRuleEngine
	isSet bool
}

func (v NullableResponseFirewallRuleEngine) Get() *ResponseFirewallRuleEngine {
	return v.value
}

func (v *NullableResponseFirewallRuleEngine) Set(val *ResponseFirewallRuleEngine) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseFirewallRuleEngine) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseFirewallRuleEngine) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseFirewallRuleEngine(val *ResponseFirewallRuleEngine) *NullableResponseFirewallRuleEngine {
	return &NullableResponseFirewallRuleEngine{value: val, isSet: true}
}

func (v NullableResponseFirewallRuleEngine) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseFirewallRuleEngine) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


