/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FirewallRuleEngineRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FirewallRuleEngineRequest{}

// FirewallRuleEngineRequest struct for FirewallRuleEngineRequest
type FirewallRuleEngineRequest struct {
	Name string `json:"name" validate:"regexp=.*"`
	Active *bool `json:"active,omitempty"`
	Criteria [][]EdgeFirewallCriterionFieldRequest `json:"criteria"`
	Behaviors []FirewallBehaviorsRequest `json:"behaviors"`
	Description *string `json:"description,omitempty" validate:"regexp=.*"`
}

type _FirewallRuleEngineRequest FirewallRuleEngineRequest

// NewFirewallRuleEngineRequest instantiates a new FirewallRuleEngineRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirewallRuleEngineRequest(name string, criteria [][]EdgeFirewallCriterionFieldRequest, behaviors []FirewallBehaviorsRequest) *FirewallRuleEngineRequest {
	this := FirewallRuleEngineRequest{}
	this.Name = name
	var active bool = true
	this.Active = &active
	this.Criteria = criteria
	this.Behaviors = behaviors
	return &this
}

// NewFirewallRuleEngineRequestWithDefaults instantiates a new FirewallRuleEngineRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirewallRuleEngineRequestWithDefaults() *FirewallRuleEngineRequest {
	this := FirewallRuleEngineRequest{}
	var active bool = true
	this.Active = &active
	return &this
}

// GetName returns the Name field value
func (o *FirewallRuleEngineRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FirewallRuleEngineRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FirewallRuleEngineRequest) SetName(v string) {
	o.Name = v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *FirewallRuleEngineRequest) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRuleEngineRequest) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *FirewallRuleEngineRequest) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *FirewallRuleEngineRequest) SetActive(v bool) {
	o.Active = &v
}

// GetCriteria returns the Criteria field value
func (o *FirewallRuleEngineRequest) GetCriteria() [][]EdgeFirewallCriterionFieldRequest {
	if o == nil {
		var ret [][]EdgeFirewallCriterionFieldRequest
		return ret
	}

	return o.Criteria
}

// GetCriteriaOk returns a tuple with the Criteria field value
// and a boolean to check if the value has been set.
func (o *FirewallRuleEngineRequest) GetCriteriaOk() ([][]EdgeFirewallCriterionFieldRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Criteria, true
}

// SetCriteria sets field value
func (o *FirewallRuleEngineRequest) SetCriteria(v [][]EdgeFirewallCriterionFieldRequest) {
	o.Criteria = v
}

// GetBehaviors returns the Behaviors field value
func (o *FirewallRuleEngineRequest) GetBehaviors() []FirewallBehaviorsRequest {
	if o == nil {
		var ret []FirewallBehaviorsRequest
		return ret
	}

	return o.Behaviors
}

// GetBehaviorsOk returns a tuple with the Behaviors field value
// and a boolean to check if the value has been set.
func (o *FirewallRuleEngineRequest) GetBehaviorsOk() ([]FirewallBehaviorsRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Behaviors, true
}

// SetBehaviors sets field value
func (o *FirewallRuleEngineRequest) SetBehaviors(v []FirewallBehaviorsRequest) {
	o.Behaviors = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *FirewallRuleEngineRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRuleEngineRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *FirewallRuleEngineRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *FirewallRuleEngineRequest) SetDescription(v string) {
	o.Description = &v
}

func (o FirewallRuleEngineRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FirewallRuleEngineRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	toSerialize["criteria"] = o.Criteria
	toSerialize["behaviors"] = o.Behaviors
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *FirewallRuleEngineRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"criteria",
		"behaviors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFirewallRuleEngineRequest := _FirewallRuleEngineRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFirewallRuleEngineRequest)

	if err != nil {
		return err
	}

	*o = FirewallRuleEngineRequest(varFirewallRuleEngineRequest)

	return err
}

type NullableFirewallRuleEngineRequest struct {
	value *FirewallRuleEngineRequest
	isSet bool
}

func (v NullableFirewallRuleEngineRequest) Get() *FirewallRuleEngineRequest {
	return v.value
}

func (v *NullableFirewallRuleEngineRequest) Set(val *FirewallRuleEngineRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFirewallRuleEngineRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFirewallRuleEngineRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirewallRuleEngineRequest(val *FirewallRuleEngineRequest) *NullableFirewallRuleEngineRequest {
	return &NullableFirewallRuleEngineRequest{value: val, isSet: true}
}

func (v NullableFirewallRuleEngineRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirewallRuleEngineRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


