/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString{}

// ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString struct for ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString
type ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString struct {
	Type ApplicationRuleEngineStringTypeEnum `json:"type"`
	Attributes ApplicationRuleEngineStringAttributes `json:"attributes"`
	AdditionalProperties map[string]interface{}
}

type _ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString

// NewApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString instantiates a new ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString(type_ ApplicationRuleEngineStringTypeEnum, attributes ApplicationRuleEngineStringAttributes) *ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString {
	this := ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineStringWithDefaults instantiates a new ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineStringWithDefaults() *ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString {
	this := ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString{}
	return &this
}

// GetType returns the Type field value
func (o *ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString) GetType() ApplicationRuleEngineStringTypeEnum {
	if o == nil {
		var ret ApplicationRuleEngineStringTypeEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString) GetTypeOk() (*ApplicationRuleEngineStringTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString) SetType(v ApplicationRuleEngineStringTypeEnum) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString) GetAttributes() ApplicationRuleEngineStringAttributes {
	if o == nil {
		var ret ApplicationRuleEngineStringAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString) GetAttributesOk() (*ApplicationRuleEngineStringAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString) SetAttributes(v ApplicationRuleEngineStringAttributes) {
	o.Attributes = v
}

func (o ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString := _ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString{}

	err = json.Unmarshal(data, &varApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString)

	if err != nil {
		return err
	}

	*o = ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString(varApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "attributes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString struct {
	value *ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString
	isSet bool
}

func (v NullableApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString) Get() *ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString {
	return v.value
}

func (v *NullableApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString) Set(val *ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString(val *ApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString) *NullableApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString {
	return &NullableApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString{value: val, isSet: true}
}

func (v NullableApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationRuleEngineRequestPhaseBehaviorsApplicationRuleEngineString) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


