/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApplicationRuleEngineSetCachePolicyTypeEnum type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationRuleEngineSetCachePolicyTypeEnum{}

// ApplicationRuleEngineSetCachePolicyTypeEnum * `set_cache_policy` - set_cache_policy
type ApplicationRuleEngineSetCachePolicyTypeEnum struct {
	AdditionalProperties map[string]interface{}
}

type _ApplicationRuleEngineSetCachePolicyTypeEnum ApplicationRuleEngineSetCachePolicyTypeEnum

// NewApplicationRuleEngineSetCachePolicyTypeEnum instantiates a new ApplicationRuleEngineSetCachePolicyTypeEnum object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationRuleEngineSetCachePolicyTypeEnum() *ApplicationRuleEngineSetCachePolicyTypeEnum {
	this := ApplicationRuleEngineSetCachePolicyTypeEnum{}
	return &this
}

// NewApplicationRuleEngineSetCachePolicyTypeEnumWithDefaults instantiates a new ApplicationRuleEngineSetCachePolicyTypeEnum object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationRuleEngineSetCachePolicyTypeEnumWithDefaults() *ApplicationRuleEngineSetCachePolicyTypeEnum {
	this := ApplicationRuleEngineSetCachePolicyTypeEnum{}
	return &this
}

func (o ApplicationRuleEngineSetCachePolicyTypeEnum) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationRuleEngineSetCachePolicyTypeEnum) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApplicationRuleEngineSetCachePolicyTypeEnum) UnmarshalJSON(data []byte) (err error) {
	varApplicationRuleEngineSetCachePolicyTypeEnum := _ApplicationRuleEngineSetCachePolicyTypeEnum{}

	err = json.Unmarshal(data, &varApplicationRuleEngineSetCachePolicyTypeEnum)

	if err != nil {
		return err
	}

	*o = ApplicationRuleEngineSetCachePolicyTypeEnum(varApplicationRuleEngineSetCachePolicyTypeEnum)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApplicationRuleEngineSetCachePolicyTypeEnum struct {
	value ApplicationRuleEngineSetCachePolicyTypeEnum
	isSet bool
}

func (v NullableApplicationRuleEngineSetCachePolicyTypeEnum) Get() ApplicationRuleEngineSetCachePolicyTypeEnum {
	return v.value
}

func (v *NullableApplicationRuleEngineSetCachePolicyTypeEnum) Set(val ApplicationRuleEngineSetCachePolicyTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationRuleEngineSetCachePolicyTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationRuleEngineSetCachePolicyTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationRuleEngineSetCachePolicyTypeEnum(val ApplicationRuleEngineSetCachePolicyTypeEnum) *NullableApplicationRuleEngineSetCachePolicyTypeEnum {
	return &NullableApplicationRuleEngineSetCachePolicyTypeEnum{value: val, isSet: true}
}

func (v NullableApplicationRuleEngineSetCachePolicyTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationRuleEngineSetCachePolicyTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


