/*
Orchestrator

REST API OpenAPI documentation for the Orchestrator

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orchestratorapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResponseAsyncServices type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseAsyncServices{}

// ResponseAsyncServices struct for ResponseAsyncServices
type ResponseAsyncServices struct {
	State *string `json:"state,omitempty"`
	Data Services `json:"data"`
}

type _ResponseAsyncServices ResponseAsyncServices

// NewResponseAsyncServices instantiates a new ResponseAsyncServices object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseAsyncServices(data Services) *ResponseAsyncServices {
	this := ResponseAsyncServices{}
	this.Data = data
	return &this
}

// NewResponseAsyncServicesWithDefaults instantiates a new ResponseAsyncServices object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseAsyncServicesWithDefaults() *ResponseAsyncServices {
	this := ResponseAsyncServices{}
	return &this
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ResponseAsyncServices) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseAsyncServices) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ResponseAsyncServices) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *ResponseAsyncServices) SetState(v string) {
	o.State = &v
}

// GetData returns the Data field value
func (o *ResponseAsyncServices) GetData() Services {
	if o == nil {
		var ret Services
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ResponseAsyncServices) GetDataOk() (*Services, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ResponseAsyncServices) SetData(v Services) {
	o.Data = v
}

func (o ResponseAsyncServices) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseAsyncServices) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ResponseAsyncServices) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseAsyncServices := _ResponseAsyncServices{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponseAsyncServices)

	if err != nil {
		return err
	}

	*o = ResponseAsyncServices(varResponseAsyncServices)

	return err
}

type NullableResponseAsyncServices struct {
	value *ResponseAsyncServices
	isSet bool
}

func (v NullableResponseAsyncServices) Get() *ResponseAsyncServices {
	return v.value
}

func (v *NullableResponseAsyncServices) Set(val *ResponseAsyncServices) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseAsyncServices) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseAsyncServices) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseAsyncServices(val *ResponseAsyncServices) *NullableResponseAsyncServices {
	return &NullableResponseAsyncServices{value: val, isSet: true}
}

func (v NullableResponseAsyncServices) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseAsyncServices) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


