/*
metrics-api

REST API OpenAPI documentation for the Metrics API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metricsapi

import (
	"encoding/json"
)

// checks if the PaginatedResponseListFolderList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedResponseListFolderList{}

// PaginatedResponseListFolderList struct for PaginatedResponseListFolderList
type PaginatedResponseListFolderList struct {
	Count *int64 `json:"count,omitempty"`
	Results []ResponseListFolder `json:"results,omitempty"`
}

// NewPaginatedResponseListFolderList instantiates a new PaginatedResponseListFolderList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedResponseListFolderList() *PaginatedResponseListFolderList {
	this := PaginatedResponseListFolderList{}
	return &this
}

// NewPaginatedResponseListFolderListWithDefaults instantiates a new PaginatedResponseListFolderList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedResponseListFolderListWithDefaults() *PaginatedResponseListFolderList {
	this := PaginatedResponseListFolderList{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *PaginatedResponseListFolderList) GetCount() int64 {
	if o == nil || IsNil(o.Count) {
		var ret int64
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedResponseListFolderList) GetCountOk() (*int64, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *PaginatedResponseListFolderList) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int64 and assigns it to the Count field.
func (o *PaginatedResponseListFolderList) SetCount(v int64) {
	o.Count = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *PaginatedResponseListFolderList) GetResults() []ResponseListFolder {
	if o == nil || IsNil(o.Results) {
		var ret []ResponseListFolder
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedResponseListFolderList) GetResultsOk() ([]ResponseListFolder, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *PaginatedResponseListFolderList) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []ResponseListFolder and assigns it to the Results field.
func (o *PaginatedResponseListFolderList) SetResults(v []ResponseListFolder) {
	o.Results = v
}

func (o PaginatedResponseListFolderList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedResponseListFolderList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullablePaginatedResponseListFolderList struct {
	value *PaginatedResponseListFolderList
	isSet bool
}

func (v NullablePaginatedResponseListFolderList) Get() *PaginatedResponseListFolderList {
	return v.value
}

func (v *NullablePaginatedResponseListFolderList) Set(val *PaginatedResponseListFolderList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedResponseListFolderList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedResponseListFolderList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedResponseListFolderList(val *PaginatedResponseListFolderList) *NullablePaginatedResponseListFolderList {
	return &NullablePaginatedResponseListFolderList{value: val, isSet: true}
}

func (v NullablePaginatedResponseListFolderList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedResponseListFolderList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


