/*
Metrics API

REST API OpenAPI documentation for the Metrics API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metricsapi

import (
	"encoding/json"
)

// checks if the ResponseAsyncDeleteReport type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseAsyncDeleteReport{}

// ResponseAsyncDeleteReport struct for ResponseAsyncDeleteReport
type ResponseAsyncDeleteReport struct {
	State *string `json:"state,omitempty"`
}

// NewResponseAsyncDeleteReport instantiates a new ResponseAsyncDeleteReport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseAsyncDeleteReport() *ResponseAsyncDeleteReport {
	this := ResponseAsyncDeleteReport{}
	return &this
}

// NewResponseAsyncDeleteReportWithDefaults instantiates a new ResponseAsyncDeleteReport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseAsyncDeleteReportWithDefaults() *ResponseAsyncDeleteReport {
	this := ResponseAsyncDeleteReport{}
	return &this
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ResponseAsyncDeleteReport) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseAsyncDeleteReport) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ResponseAsyncDeleteReport) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *ResponseAsyncDeleteReport) SetState(v string) {
	o.State = &v
}

func (o ResponseAsyncDeleteReport) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseAsyncDeleteReport) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

type NullableResponseAsyncDeleteReport struct {
	value *ResponseAsyncDeleteReport
	isSet bool
}

func (v NullableResponseAsyncDeleteReport) Get() *ResponseAsyncDeleteReport {
	return v.value
}

func (v *NullableResponseAsyncDeleteReport) Set(val *ResponseAsyncDeleteReport) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseAsyncDeleteReport) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseAsyncDeleteReport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseAsyncDeleteReport(val *ResponseAsyncDeleteReport) *NullableResponseAsyncDeleteReport {
	return &NullableResponseAsyncDeleteReport{value: val, isSet: true}
}

func (v NullableResponseAsyncDeleteReport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseAsyncDeleteReport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


