/*
azion-api

The AZION v4 REST API.

API version: 4.0.0
Contact: support@azion.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package azionapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaymentHistory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentHistory{}

// PaymentHistory struct for PaymentHistory
type PaymentHistory struct {
	AmountWithCurrency string `json:"amount_with_currency"`
	InvoiceNumber NullableString `json:"invoice_number"`
	InvoiceUrl NullableString `json:"invoice_url"`
	Status string `json:"status"`
	PaymentDue string `json:"payment_due"`
	CardBrand NullableString `json:"card_brand"`
	PaymentMethodDetails NullableString `json:"payment_method_details"`
}

type _PaymentHistory PaymentHistory

// NewPaymentHistory instantiates a new PaymentHistory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentHistory(amountWithCurrency string, invoiceNumber NullableString, invoiceUrl NullableString, status string, paymentDue string, cardBrand NullableString, paymentMethodDetails NullableString) *PaymentHistory {
	this := PaymentHistory{}
	this.AmountWithCurrency = amountWithCurrency
	this.InvoiceNumber = invoiceNumber
	this.InvoiceUrl = invoiceUrl
	this.Status = status
	this.PaymentDue = paymentDue
	this.CardBrand = cardBrand
	this.PaymentMethodDetails = paymentMethodDetails
	return &this
}

// NewPaymentHistoryWithDefaults instantiates a new PaymentHistory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentHistoryWithDefaults() *PaymentHistory {
	this := PaymentHistory{}
	return &this
}

// GetAmountWithCurrency returns the AmountWithCurrency field value
func (o *PaymentHistory) GetAmountWithCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AmountWithCurrency
}

// GetAmountWithCurrencyOk returns a tuple with the AmountWithCurrency field value
// and a boolean to check if the value has been set.
func (o *PaymentHistory) GetAmountWithCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountWithCurrency, true
}

// SetAmountWithCurrency sets field value
func (o *PaymentHistory) SetAmountWithCurrency(v string) {
	o.AmountWithCurrency = v
}

// GetInvoiceNumber returns the InvoiceNumber field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PaymentHistory) GetInvoiceNumber() string {
	if o == nil || o.InvoiceNumber.Get() == nil {
		var ret string
		return ret
	}

	return *o.InvoiceNumber.Get()
}

// GetInvoiceNumberOk returns a tuple with the InvoiceNumber field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentHistory) GetInvoiceNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InvoiceNumber.Get(), o.InvoiceNumber.IsSet()
}

// SetInvoiceNumber sets field value
func (o *PaymentHistory) SetInvoiceNumber(v string) {
	o.InvoiceNumber.Set(&v)
}

// GetInvoiceUrl returns the InvoiceUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PaymentHistory) GetInvoiceUrl() string {
	if o == nil || o.InvoiceUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.InvoiceUrl.Get()
}

// GetInvoiceUrlOk returns a tuple with the InvoiceUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentHistory) GetInvoiceUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InvoiceUrl.Get(), o.InvoiceUrl.IsSet()
}

// SetInvoiceUrl sets field value
func (o *PaymentHistory) SetInvoiceUrl(v string) {
	o.InvoiceUrl.Set(&v)
}

// GetStatus returns the Status field value
func (o *PaymentHistory) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PaymentHistory) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PaymentHistory) SetStatus(v string) {
	o.Status = v
}

// GetPaymentDue returns the PaymentDue field value
func (o *PaymentHistory) GetPaymentDue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaymentDue
}

// GetPaymentDueOk returns a tuple with the PaymentDue field value
// and a boolean to check if the value has been set.
func (o *PaymentHistory) GetPaymentDueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentDue, true
}

// SetPaymentDue sets field value
func (o *PaymentHistory) SetPaymentDue(v string) {
	o.PaymentDue = v
}

// GetCardBrand returns the CardBrand field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PaymentHistory) GetCardBrand() string {
	if o == nil || o.CardBrand.Get() == nil {
		var ret string
		return ret
	}

	return *o.CardBrand.Get()
}

// GetCardBrandOk returns a tuple with the CardBrand field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentHistory) GetCardBrandOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CardBrand.Get(), o.CardBrand.IsSet()
}

// SetCardBrand sets field value
func (o *PaymentHistory) SetCardBrand(v string) {
	o.CardBrand.Set(&v)
}

// GetPaymentMethodDetails returns the PaymentMethodDetails field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PaymentHistory) GetPaymentMethodDetails() string {
	if o == nil || o.PaymentMethodDetails.Get() == nil {
		var ret string
		return ret
	}

	return *o.PaymentMethodDetails.Get()
}

// GetPaymentMethodDetailsOk returns a tuple with the PaymentMethodDetails field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentHistory) GetPaymentMethodDetailsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PaymentMethodDetails.Get(), o.PaymentMethodDetails.IsSet()
}

// SetPaymentMethodDetails sets field value
func (o *PaymentHistory) SetPaymentMethodDetails(v string) {
	o.PaymentMethodDetails.Set(&v)
}

func (o PaymentHistory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentHistory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount_with_currency"] = o.AmountWithCurrency
	toSerialize["invoice_number"] = o.InvoiceNumber.Get()
	toSerialize["invoice_url"] = o.InvoiceUrl.Get()
	toSerialize["status"] = o.Status
	toSerialize["payment_due"] = o.PaymentDue
	toSerialize["card_brand"] = o.CardBrand.Get()
	toSerialize["payment_method_details"] = o.PaymentMethodDetails.Get()
	return toSerialize, nil
}

func (o *PaymentHistory) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount_with_currency",
		"invoice_number",
		"invoice_url",
		"status",
		"payment_due",
		"card_brand",
		"payment_method_details",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentHistory := _PaymentHistory{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaymentHistory)

	if err != nil {
		return err
	}

	*o = PaymentHistory(varPaymentHistory)

	return err
}

type NullablePaymentHistory struct {
	value *PaymentHistory
	isSet bool
}

func (v NullablePaymentHistory) Get() *PaymentHistory {
	return v.value
}

func (v *NullablePaymentHistory) Set(val *PaymentHistory) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentHistory) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentHistory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentHistory(val *PaymentHistory) *NullablePaymentHistory {
	return &NullablePaymentHistory{value: val, isSet: true}
}

func (v NullablePaymentHistory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentHistory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


