/*
azion-api

The AZION v4 REST API.

API version: 4.0.0
Contact: support@azion.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package azionapi

import (
	"encoding/json"
)

// checks if the BehaviorArgsAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BehaviorArgsAttributes{}

// BehaviorArgsAttributes Behavior attributes containing the value parameter
type BehaviorArgsAttributes struct {
	Value BehaviorArgsAttributesValue `json:"value"`
}

type _BehaviorArgsAttributes BehaviorArgsAttributes

// NewBehaviorArgsAttributes instantiates a new BehaviorArgsAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBehaviorArgsAttributes(value BehaviorArgsAttributesValue) *BehaviorArgsAttributes {
	this := BehaviorArgsAttributes{}
	this.Value = value
	return &this
}

// NewBehaviorArgsAttributesWithDefaults instantiates a new BehaviorArgsAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBehaviorArgsAttributesWithDefaults() *BehaviorArgsAttributes {
	this := BehaviorArgsAttributes{}
	return &this
}

// GetValue returns the Value field value
func (o *BehaviorArgsAttributes) GetValue() BehaviorArgsAttributesValue {
	if o == nil {
		var ret BehaviorArgsAttributesValue
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *BehaviorArgsAttributes) GetValueOk() (*BehaviorArgsAttributesValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *BehaviorArgsAttributes) SetValue(v BehaviorArgsAttributesValue) {
	o.Value = v
}

func (o BehaviorArgsAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BehaviorArgsAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

type NullableBehaviorArgsAttributes struct {
	value *BehaviorArgsAttributes
	isSet bool
}

func (v NullableBehaviorArgsAttributes) Get() *BehaviorArgsAttributes {
	return v.value
}

func (v *NullableBehaviorArgsAttributes) Set(val *BehaviorArgsAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableBehaviorArgsAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableBehaviorArgsAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBehaviorArgsAttributes(val *BehaviorArgsAttributes) *NullableBehaviorArgsAttributes {
	return &NullableBehaviorArgsAttributes{value: val, isSet: true}
}

func (v NullableBehaviorArgsAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBehaviorArgsAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


