/*
azion-api

The AZION v4 REST API.

API version: 4.0.0
Contact: support@azion.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package azionapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FunctionsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FunctionsRequest{}

// FunctionsRequest struct for FunctionsRequest
type FunctionsRequest struct {
	Name string `json:"name"`
	Active *bool `json:"active,omitempty"`
	// * `azion_js` - Azion JavaScript
	Runtime *string `json:"runtime,omitempty"`
	// * `firewall` - Firewall * `application` - Application
	ExecutionEnvironment *string `json:"execution_environment,omitempty"`
	// String containing the function code. Maximum size: 20MB.
	Code string `json:"code"`
	DefaultArgs interface{} `json:"default_args,omitempty"`
	AzionForm *FunctionsAzionForm `json:"azion_form,omitempty"`
}

type _FunctionsRequest FunctionsRequest

// NewFunctionsRequest instantiates a new FunctionsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFunctionsRequest(name string, code string) *FunctionsRequest {
	this := FunctionsRequest{}
	this.Name = name
	this.Code = code
	return &this
}

// NewFunctionsRequestWithDefaults instantiates a new FunctionsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFunctionsRequestWithDefaults() *FunctionsRequest {
	this := FunctionsRequest{}
	return &this
}

// GetName returns the Name field value
func (o *FunctionsRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FunctionsRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FunctionsRequest) SetName(v string) {
	o.Name = v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *FunctionsRequest) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunctionsRequest) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *FunctionsRequest) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *FunctionsRequest) SetActive(v bool) {
	o.Active = &v
}

// GetRuntime returns the Runtime field value if set, zero value otherwise.
func (o *FunctionsRequest) GetRuntime() string {
	if o == nil || IsNil(o.Runtime) {
		var ret string
		return ret
	}
	return *o.Runtime
}

// GetRuntimeOk returns a tuple with the Runtime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunctionsRequest) GetRuntimeOk() (*string, bool) {
	if o == nil || IsNil(o.Runtime) {
		return nil, false
	}
	return o.Runtime, true
}

// HasRuntime returns a boolean if a field has been set.
func (o *FunctionsRequest) HasRuntime() bool {
	if o != nil && !IsNil(o.Runtime) {
		return true
	}

	return false
}

// SetRuntime gets a reference to the given string and assigns it to the Runtime field.
func (o *FunctionsRequest) SetRuntime(v string) {
	o.Runtime = &v
}

// GetExecutionEnvironment returns the ExecutionEnvironment field value if set, zero value otherwise.
func (o *FunctionsRequest) GetExecutionEnvironment() string {
	if o == nil || IsNil(o.ExecutionEnvironment) {
		var ret string
		return ret
	}
	return *o.ExecutionEnvironment
}

// GetExecutionEnvironmentOk returns a tuple with the ExecutionEnvironment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunctionsRequest) GetExecutionEnvironmentOk() (*string, bool) {
	if o == nil || IsNil(o.ExecutionEnvironment) {
		return nil, false
	}
	return o.ExecutionEnvironment, true
}

// HasExecutionEnvironment returns a boolean if a field has been set.
func (o *FunctionsRequest) HasExecutionEnvironment() bool {
	if o != nil && !IsNil(o.ExecutionEnvironment) {
		return true
	}

	return false
}

// SetExecutionEnvironment gets a reference to the given string and assigns it to the ExecutionEnvironment field.
func (o *FunctionsRequest) SetExecutionEnvironment(v string) {
	o.ExecutionEnvironment = &v
}

// GetCode returns the Code field value
func (o *FunctionsRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *FunctionsRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *FunctionsRequest) SetCode(v string) {
	o.Code = v
}

// GetDefaultArgs returns the DefaultArgs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FunctionsRequest) GetDefaultArgs() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.DefaultArgs
}

// GetDefaultArgsOk returns a tuple with the DefaultArgs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FunctionsRequest) GetDefaultArgsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.DefaultArgs) {
		return nil, false
	}
	return &o.DefaultArgs, true
}

// HasDefaultArgs returns a boolean if a field has been set.
func (o *FunctionsRequest) HasDefaultArgs() bool {
	if o != nil && !IsNil(o.DefaultArgs) {
		return true
	}

	return false
}

// SetDefaultArgs gets a reference to the given interface{} and assigns it to the DefaultArgs field.
func (o *FunctionsRequest) SetDefaultArgs(v interface{}) {
	o.DefaultArgs = v
}

// GetAzionForm returns the AzionForm field value if set, zero value otherwise.
func (o *FunctionsRequest) GetAzionForm() FunctionsAzionForm {
	if o == nil || IsNil(o.AzionForm) {
		var ret FunctionsAzionForm
		return ret
	}
	return *o.AzionForm
}

// GetAzionFormOk returns a tuple with the AzionForm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunctionsRequest) GetAzionFormOk() (*FunctionsAzionForm, bool) {
	if o == nil || IsNil(o.AzionForm) {
		return nil, false
	}
	return o.AzionForm, true
}

// HasAzionForm returns a boolean if a field has been set.
func (o *FunctionsRequest) HasAzionForm() bool {
	if o != nil && !IsNil(o.AzionForm) {
		return true
	}

	return false
}

// SetAzionForm gets a reference to the given FunctionsAzionForm and assigns it to the AzionForm field.
func (o *FunctionsRequest) SetAzionForm(v FunctionsAzionForm) {
	o.AzionForm = &v
}

func (o FunctionsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FunctionsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Runtime) {
		toSerialize["runtime"] = o.Runtime
	}
	if !IsNil(o.ExecutionEnvironment) {
		toSerialize["execution_environment"] = o.ExecutionEnvironment
	}
	toSerialize["code"] = o.Code
	if o.DefaultArgs != nil {
		toSerialize["default_args"] = o.DefaultArgs
	}
	if !IsNil(o.AzionForm) {
		toSerialize["azion_form"] = o.AzionForm
	}
	return toSerialize, nil
}

func (o *FunctionsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFunctionsRequest := _FunctionsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFunctionsRequest)

	if err != nil {
		return err
	}

	*o = FunctionsRequest(varFunctionsRequest)

	return err
}

type NullableFunctionsRequest struct {
	value *FunctionsRequest
	isSet bool
}

func (v NullableFunctionsRequest) Get() *FunctionsRequest {
	return v.value
}

func (v *NullableFunctionsRequest) Set(val *FunctionsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFunctionsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFunctionsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFunctionsRequest(val *FunctionsRequest) *NullableFunctionsRequest {
	return &NullableFunctionsRequest{value: val, isSet: true}
}

func (v NullableFunctionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFunctionsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


