/*
azion-api

The AZION v4 REST API.

API version: 4.0.0
Contact: support@azion.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package azionapi

import (
	"encoding/json"
)

// checks if the ResponseTool type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseTool{}

// ResponseTool struct for ResponseTool
type ResponseTool struct {
	State *string `json:"state,omitempty"`
	Data Tool `json:"data"`
}

type _ResponseTool ResponseTool

// NewResponseTool instantiates a new ResponseTool object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseTool(data Tool) *ResponseTool {
	this := ResponseTool{}
	this.Data = data
	return &this
}

// NewResponseToolWithDefaults instantiates a new ResponseTool object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseToolWithDefaults() *ResponseTool {
	this := ResponseTool{}
	return &this
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ResponseTool) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseTool) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ResponseTool) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *ResponseTool) SetState(v string) {
	o.State = &v
}

// GetData returns the Data field value
func (o *ResponseTool) GetData() Tool {
	if o == nil {
		var ret Tool
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ResponseTool) GetDataOk() (*Tool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ResponseTool) SetData(v Tool) {
	o.Data = v
}

func (o ResponseTool) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseTool) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableResponseTool struct {
	value *ResponseTool
	isSet bool
}

func (v NullableResponseTool) Get() *ResponseTool {
	return v.value
}

func (v *NullableResponseTool) Set(val *ResponseTool) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseTool) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseTool) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseTool(val *ResponseTool) *NullableResponseTool {
	return &NullableResponseTool{value: val, isSet: true}
}

func (v NullableResponseTool) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseTool) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


