/*
azion-api

The AZION v4 REST API.

API version: 4.0.0
Contact: support@azion.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package azionapi

import (
	"encoding/json"
	"fmt"
)

// checks if the FirewallBehaviorSetRateLimit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FirewallBehaviorSetRateLimit{}

// FirewallBehaviorSetRateLimit Set a rate limit
type FirewallBehaviorSetRateLimit struct {
	// * `set_rate_limit` - set_rate_limit
	Type string `json:"type"`
	Attributes FirewallBehaviorSetRateLimitAttributes `json:"attributes"`
	AdditionalProperties map[string]interface{}
}

type _FirewallBehaviorSetRateLimit FirewallBehaviorSetRateLimit

// NewFirewallBehaviorSetRateLimit instantiates a new FirewallBehaviorSetRateLimit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirewallBehaviorSetRateLimit(type_ string, attributes FirewallBehaviorSetRateLimitAttributes) *FirewallBehaviorSetRateLimit {
	this := FirewallBehaviorSetRateLimit{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewFirewallBehaviorSetRateLimitWithDefaults instantiates a new FirewallBehaviorSetRateLimit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirewallBehaviorSetRateLimitWithDefaults() *FirewallBehaviorSetRateLimit {
	this := FirewallBehaviorSetRateLimit{}
	return &this
}

// GetType returns the Type field value
func (o *FirewallBehaviorSetRateLimit) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *FirewallBehaviorSetRateLimit) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *FirewallBehaviorSetRateLimit) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *FirewallBehaviorSetRateLimit) GetAttributes() FirewallBehaviorSetRateLimitAttributes {
	if o == nil {
		var ret FirewallBehaviorSetRateLimitAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *FirewallBehaviorSetRateLimit) GetAttributesOk() (*FirewallBehaviorSetRateLimitAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *FirewallBehaviorSetRateLimit) SetAttributes(v FirewallBehaviorSetRateLimitAttributes) {
	o.Attributes = v
}

func (o FirewallBehaviorSetRateLimit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FirewallBehaviorSetRateLimit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FirewallBehaviorSetRateLimit) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFirewallBehaviorSetRateLimit := _FirewallBehaviorSetRateLimit{}

	err = json.Unmarshal(data, &varFirewallBehaviorSetRateLimit)

	if err != nil {
		return err
	}

	*o = FirewallBehaviorSetRateLimit(varFirewallBehaviorSetRateLimit)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "attributes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFirewallBehaviorSetRateLimit struct {
	value *FirewallBehaviorSetRateLimit
	isSet bool
}

func (v NullableFirewallBehaviorSetRateLimit) Get() *FirewallBehaviorSetRateLimit {
	return v.value
}

func (v *NullableFirewallBehaviorSetRateLimit) Set(val *FirewallBehaviorSetRateLimit) {
	v.value = val
	v.isSet = true
}

func (v NullableFirewallBehaviorSetRateLimit) IsSet() bool {
	return v.isSet
}

func (v *NullableFirewallBehaviorSetRateLimit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirewallBehaviorSetRateLimit(val *FirewallBehaviorSetRateLimit) *NullableFirewallBehaviorSetRateLimit {
	return &NullableFirewallBehaviorSetRateLimit{value: val, isSet: true}
}

func (v NullableFirewallBehaviorSetRateLimit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirewallBehaviorSetRateLimit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


