/*
azion-api

The AZION v4 REST API.

API version: 4.0.0
Contact: support@azion.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package azionapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InputInputDataSourceAttributesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputInputDataSourceAttributesRequest{}

// InputInputDataSourceAttributesRequest struct for InputInputDataSourceAttributesRequest
type InputInputDataSourceAttributesRequest struct {
	// Type identifier for this endpoint (raw_logs)
	Type string `json:"type"`
	Attributes InputDataSourceRequest `json:"attributes"`
}

type _InputInputDataSourceAttributesRequest InputInputDataSourceAttributesRequest

// NewInputInputDataSourceAttributesRequest instantiates a new InputInputDataSourceAttributesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputInputDataSourceAttributesRequest(type_ string, attributes InputDataSourceRequest) *InputInputDataSourceAttributesRequest {
	this := InputInputDataSourceAttributesRequest{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewInputInputDataSourceAttributesRequestWithDefaults instantiates a new InputInputDataSourceAttributesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputInputDataSourceAttributesRequestWithDefaults() *InputInputDataSourceAttributesRequest {
	this := InputInputDataSourceAttributesRequest{}
	return &this
}

// GetType returns the Type field value
func (o *InputInputDataSourceAttributesRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *InputInputDataSourceAttributesRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InputInputDataSourceAttributesRequest) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *InputInputDataSourceAttributesRequest) GetAttributes() InputDataSourceRequest {
	if o == nil {
		var ret InputDataSourceRequest
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *InputInputDataSourceAttributesRequest) GetAttributesOk() (*InputDataSourceRequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *InputInputDataSourceAttributesRequest) SetAttributes(v InputDataSourceRequest) {
	o.Attributes = v
}

func (o InputInputDataSourceAttributesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputInputDataSourceAttributesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *InputInputDataSourceAttributesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputInputDataSourceAttributesRequest := _InputInputDataSourceAttributesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputInputDataSourceAttributesRequest)

	if err != nil {
		return err
	}

	*o = InputInputDataSourceAttributesRequest(varInputInputDataSourceAttributesRequest)

	return err
}

type NullableInputInputDataSourceAttributesRequest struct {
	value *InputInputDataSourceAttributesRequest
	isSet bool
}

func (v NullableInputInputDataSourceAttributesRequest) Get() *InputInputDataSourceAttributesRequest {
	return v.value
}

func (v *NullableInputInputDataSourceAttributesRequest) Set(val *InputInputDataSourceAttributesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInputInputDataSourceAttributesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInputInputDataSourceAttributesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputInputDataSourceAttributesRequest(val *InputInputDataSourceAttributesRequest) *NullableInputInputDataSourceAttributesRequest {
	return &NullableInputInputDataSourceAttributesRequest{value: val, isSet: true}
}

func (v NullableInputInputDataSourceAttributesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputInputDataSourceAttributesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


