/*
azion-api

The AZION v4 REST API.

API version: 4.0.0
Contact: support@azion.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package azionapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KBAskResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KBAskResponse{}

// KBAskResponse struct for KBAskResponse
type KBAskResponse struct {
	Answer string `json:"answer"`
	Context []KBQueryResult `json:"context"`
}

type _KBAskResponse KBAskResponse

// NewKBAskResponse instantiates a new KBAskResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKBAskResponse(answer string, context []KBQueryResult) *KBAskResponse {
	this := KBAskResponse{}
	this.Answer = answer
	this.Context = context
	return &this
}

// NewKBAskResponseWithDefaults instantiates a new KBAskResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKBAskResponseWithDefaults() *KBAskResponse {
	this := KBAskResponse{}
	return &this
}

// GetAnswer returns the Answer field value
func (o *KBAskResponse) GetAnswer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Answer
}

// GetAnswerOk returns a tuple with the Answer field value
// and a boolean to check if the value has been set.
func (o *KBAskResponse) GetAnswerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Answer, true
}

// SetAnswer sets field value
func (o *KBAskResponse) SetAnswer(v string) {
	o.Answer = v
}

// GetContext returns the Context field value
func (o *KBAskResponse) GetContext() []KBQueryResult {
	if o == nil {
		var ret []KBQueryResult
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *KBAskResponse) GetContextOk() ([]KBQueryResult, bool) {
	if o == nil {
		return nil, false
	}
	return o.Context, true
}

// SetContext sets field value
func (o *KBAskResponse) SetContext(v []KBQueryResult) {
	o.Context = v
}

func (o KBAskResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KBAskResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["answer"] = o.Answer
	toSerialize["context"] = o.Context
	return toSerialize, nil
}

func (o *KBAskResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"answer",
		"context",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKBAskResponse := _KBAskResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKBAskResponse)

	if err != nil {
		return err
	}

	*o = KBAskResponse(varKBAskResponse)

	return err
}

type NullableKBAskResponse struct {
	value *KBAskResponse
	isSet bool
}

func (v NullableKBAskResponse) Get() *KBAskResponse {
	return v.value
}

func (v *NullableKBAskResponse) Set(val *KBAskResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableKBAskResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableKBAskResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKBAskResponse(val *KBAskResponse) *NullableKBAskResponse {
	return &NullableKBAskResponse{value: val, isSet: true}
}

func (v NullableKBAskResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKBAskResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


