/*
storage-api

REST API OpenAPI documentation for the Storage

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storageapi

import (
	"encoding/json"
)

// checks if the PaginatedCredentialList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedCredentialList{}

// PaginatedCredentialList struct for PaginatedCredentialList
type PaginatedCredentialList struct {
	// Total number of items
	Count *int64 `json:"count,omitempty"`
	// Total number of pages
	TotalPages *int64 `json:"total_pages,omitempty"`
	// Current page number
	Page *int64 `json:"page,omitempty"`
	// Number of items per page
	PageSize *int64 `json:"page_size,omitempty"`
	Results []Credential `json:"results,omitempty"`
}

// NewPaginatedCredentialList instantiates a new PaginatedCredentialList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedCredentialList() *PaginatedCredentialList {
	this := PaginatedCredentialList{}
	return &this
}

// NewPaginatedCredentialListWithDefaults instantiates a new PaginatedCredentialList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedCredentialListWithDefaults() *PaginatedCredentialList {
	this := PaginatedCredentialList{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *PaginatedCredentialList) GetCount() int64 {
	if o == nil || IsNil(o.Count) {
		var ret int64
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedCredentialList) GetCountOk() (*int64, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *PaginatedCredentialList) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int64 and assigns it to the Count field.
func (o *PaginatedCredentialList) SetCount(v int64) {
	o.Count = &v
}

// GetTotalPages returns the TotalPages field value if set, zero value otherwise.
func (o *PaginatedCredentialList) GetTotalPages() int64 {
	if o == nil || IsNil(o.TotalPages) {
		var ret int64
		return ret
	}
	return *o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedCredentialList) GetTotalPagesOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalPages) {
		return nil, false
	}
	return o.TotalPages, true
}

// HasTotalPages returns a boolean if a field has been set.
func (o *PaginatedCredentialList) HasTotalPages() bool {
	if o != nil && !IsNil(o.TotalPages) {
		return true
	}

	return false
}

// SetTotalPages gets a reference to the given int64 and assigns it to the TotalPages field.
func (o *PaginatedCredentialList) SetTotalPages(v int64) {
	o.TotalPages = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *PaginatedCredentialList) GetPage() int64 {
	if o == nil || IsNil(o.Page) {
		var ret int64
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedCredentialList) GetPageOk() (*int64, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *PaginatedCredentialList) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int64 and assigns it to the Page field.
func (o *PaginatedCredentialList) SetPage(v int64) {
	o.Page = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *PaginatedCredentialList) GetPageSize() int64 {
	if o == nil || IsNil(o.PageSize) {
		var ret int64
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedCredentialList) GetPageSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *PaginatedCredentialList) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int64 and assigns it to the PageSize field.
func (o *PaginatedCredentialList) SetPageSize(v int64) {
	o.PageSize = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *PaginatedCredentialList) GetResults() []Credential {
	if o == nil || IsNil(o.Results) {
		var ret []Credential
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedCredentialList) GetResultsOk() ([]Credential, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *PaginatedCredentialList) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []Credential and assigns it to the Results field.
func (o *PaginatedCredentialList) SetResults(v []Credential) {
	o.Results = v
}

func (o PaginatedCredentialList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedCredentialList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.TotalPages) {
		toSerialize["total_pages"] = o.TotalPages
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.PageSize) {
		toSerialize["page_size"] = o.PageSize
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullablePaginatedCredentialList struct {
	value *PaginatedCredentialList
	isSet bool
}

func (v NullablePaginatedCredentialList) Get() *PaginatedCredentialList {
	return v.value
}

func (v *NullablePaginatedCredentialList) Set(val *PaginatedCredentialList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedCredentialList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedCredentialList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedCredentialList(val *PaginatedCredentialList) *NullablePaginatedCredentialList {
	return &NullablePaginatedCredentialList{value: val, isSet: true}
}

func (v NullablePaginatedCredentialList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedCredentialList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


