/*
identity-api

REST API OpenAPI documentation for the Identity API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identityapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResponseDeleteFavorite type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseDeleteFavorite{}

// ResponseDeleteFavorite struct for ResponseDeleteFavorite
type ResponseDeleteFavorite struct {
	// * `pending` - pending * `executed` - executed
	State string `json:"state"`
	Data NullableFavorite `json:"data"`
}

type _ResponseDeleteFavorite ResponseDeleteFavorite

// NewResponseDeleteFavorite instantiates a new ResponseDeleteFavorite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseDeleteFavorite(state string, data NullableFavorite) *ResponseDeleteFavorite {
	this := ResponseDeleteFavorite{}
	this.State = state
	this.Data = data
	return &this
}

// NewResponseDeleteFavoriteWithDefaults instantiates a new ResponseDeleteFavorite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseDeleteFavoriteWithDefaults() *ResponseDeleteFavorite {
	this := ResponseDeleteFavorite{}
	return &this
}

// GetState returns the State field value
func (o *ResponseDeleteFavorite) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ResponseDeleteFavorite) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ResponseDeleteFavorite) SetState(v string) {
	o.State = v
}

// GetData returns the Data field value
// If the value is explicit nil, the zero value for Favorite will be returned
func (o *ResponseDeleteFavorite) GetData() Favorite {
	if o == nil || o.Data.Get() == nil {
		var ret Favorite
		return ret
	}

	return *o.Data.Get()
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponseDeleteFavorite) GetDataOk() (*Favorite, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data.Get(), o.Data.IsSet()
}

// SetData sets field value
func (o *ResponseDeleteFavorite) SetData(v Favorite) {
	o.Data.Set(&v)
}

func (o ResponseDeleteFavorite) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseDeleteFavorite) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	toSerialize["data"] = o.Data.Get()
	return toSerialize, nil
}

func (o *ResponseDeleteFavorite) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseDeleteFavorite := _ResponseDeleteFavorite{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponseDeleteFavorite)

	if err != nil {
		return err
	}

	*o = ResponseDeleteFavorite(varResponseDeleteFavorite)

	return err
}

type NullableResponseDeleteFavorite struct {
	value *ResponseDeleteFavorite
	isSet bool
}

func (v NullableResponseDeleteFavorite) Get() *ResponseDeleteFavorite {
	return v.value
}

func (v *NullableResponseDeleteFavorite) Set(val *ResponseDeleteFavorite) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseDeleteFavorite) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseDeleteFavorite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseDeleteFavorite(val *ResponseDeleteFavorite) *NullableResponseDeleteFavorite {
	return &NullableResponseDeleteFavorite{value: val, isSet: true}
}

func (v NullableResponseDeleteFavorite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseDeleteFavorite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


