/*
azion-api

Testing ApplicationsRequestRulesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package azionapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_azionapi_ApplicationsRequestRulesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ApplicationsRequestRulesAPIService CreateApplicationRequestRule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var applicationId int64

		resp, httpRes, err := apiClient.ApplicationsRequestRulesAPI.CreateApplicationRequestRule(context.Background(), applicationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApplicationsRequestRulesAPIService CreateApplicationRequestRule2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var applicationId int64
		var versionId string

		resp, httpRes, err := apiClient.ApplicationsRequestRulesAPI.CreateApplicationRequestRule2(context.Background(), applicationId, versionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApplicationsRequestRulesAPIService DeleteApplicationRequestRule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var applicationId int64
		var requestRuleId int64

		resp, httpRes, err := apiClient.ApplicationsRequestRulesAPI.DeleteApplicationRequestRule(context.Background(), applicationId, requestRuleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApplicationsRequestRulesAPIService DeleteApplicationRequestRule2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var applicationId int64
		var requestRuleId int64
		var versionId string

		resp, httpRes, err := apiClient.ApplicationsRequestRulesAPI.DeleteApplicationRequestRule2(context.Background(), applicationId, requestRuleId, versionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApplicationsRequestRulesAPIService ListApplicationRequestRules", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var applicationId int64

		resp, httpRes, err := apiClient.ApplicationsRequestRulesAPI.ListApplicationRequestRules(context.Background(), applicationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApplicationsRequestRulesAPIService ListApplicationRequestRules2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var applicationId int64
		var versionId string

		resp, httpRes, err := apiClient.ApplicationsRequestRulesAPI.ListApplicationRequestRules2(context.Background(), applicationId, versionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApplicationsRequestRulesAPIService PartialUpdateApplicationRequestRule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var applicationId int64
		var requestRuleId int64

		resp, httpRes, err := apiClient.ApplicationsRequestRulesAPI.PartialUpdateApplicationRequestRule(context.Background(), applicationId, requestRuleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApplicationsRequestRulesAPIService PartialUpdateApplicationRequestRule2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var applicationId int64
		var requestRuleId int64
		var versionId string

		resp, httpRes, err := apiClient.ApplicationsRequestRulesAPI.PartialUpdateApplicationRequestRule2(context.Background(), applicationId, requestRuleId, versionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApplicationsRequestRulesAPIService RetrieveApplicationRequestRule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var applicationId int64
		var requestRuleId int64

		resp, httpRes, err := apiClient.ApplicationsRequestRulesAPI.RetrieveApplicationRequestRule(context.Background(), applicationId, requestRuleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApplicationsRequestRulesAPIService RetrieveApplicationRequestRule2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var applicationId int64
		var requestRuleId int64
		var versionId string

		resp, httpRes, err := apiClient.ApplicationsRequestRulesAPI.RetrieveApplicationRequestRule2(context.Background(), applicationId, requestRuleId, versionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApplicationsRequestRulesAPIService UpdateApplicationRequestRule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var applicationId int64
		var requestRuleId int64

		resp, httpRes, err := apiClient.ApplicationsRequestRulesAPI.UpdateApplicationRequestRule(context.Background(), applicationId, requestRuleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApplicationsRequestRulesAPIService UpdateApplicationRequestRule2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var applicationId int64
		var requestRuleId int64
		var versionId string

		resp, httpRes, err := apiClient.ApplicationsRequestRulesAPI.UpdateApplicationRequestRule2(context.Background(), applicationId, requestRuleId, versionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApplicationsRequestRulesAPIService UpdateApplicationRequestRulesOrder", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var applicationId int64

		resp, httpRes, err := apiClient.ApplicationsRequestRulesAPI.UpdateApplicationRequestRulesOrder(context.Background(), applicationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApplicationsRequestRulesAPIService UpdateApplicationRequestRulesOrder2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var applicationId int64
		var versionId string

		resp, httpRes, err := apiClient.ApplicationsRequestRulesAPI.UpdateApplicationRequestRulesOrder2(context.Background(), applicationId, versionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
