/*
azion-api

Testing IdentityGrantsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package azionapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_azionapi_IdentityGrantsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test IdentityGrantsAPIService CreateGrant", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.IdentityGrantsAPI.CreateGrant(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdentityGrantsAPIService DeleteGrant", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var grantId string

		resp, httpRes, err := apiClient.IdentityGrantsAPI.DeleteGrant(context.Background(), grantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdentityGrantsAPIService ListGrants", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.IdentityGrantsAPI.ListGrants(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdentityGrantsAPIService PartialUpdateGrant", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var grantId string

		resp, httpRes, err := apiClient.IdentityGrantsAPI.PartialUpdateGrant(context.Background(), grantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdentityGrantsAPIService RetrieveGrant", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var grantId string

		resp, httpRes, err := apiClient.IdentityGrantsAPI.RetrieveGrant(context.Background(), grantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdentityGrantsAPIService UpdateGrant", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var grantId string

		resp, httpRes, err := apiClient.IdentityGrantsAPI.UpdateGrant(context.Background(), grantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
