/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgeapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EdgeFirewallRuleEngineRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EdgeFirewallRuleEngineRequest{}

// EdgeFirewallRuleEngineRequest struct for EdgeFirewallRuleEngineRequest
type EdgeFirewallRuleEngineRequest struct {
	Name string `json:"name"`
	Active *bool `json:"active,omitempty"`
	Criteria [][]EdgeFirewallCriterionFieldRequest `json:"criteria"`
	Behaviors []EdgeFirewallBehaviorsRequest `json:"behaviors"`
	Description *string `json:"description,omitempty"`
}

type _EdgeFirewallRuleEngineRequest EdgeFirewallRuleEngineRequest

// NewEdgeFirewallRuleEngineRequest instantiates a new EdgeFirewallRuleEngineRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEdgeFirewallRuleEngineRequest(name string, criteria [][]EdgeFirewallCriterionFieldRequest, behaviors []EdgeFirewallBehaviorsRequest) *EdgeFirewallRuleEngineRequest {
	this := EdgeFirewallRuleEngineRequest{}
	this.Name = name
	this.Criteria = criteria
	this.Behaviors = behaviors
	return &this
}

// NewEdgeFirewallRuleEngineRequestWithDefaults instantiates a new EdgeFirewallRuleEngineRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEdgeFirewallRuleEngineRequestWithDefaults() *EdgeFirewallRuleEngineRequest {
	this := EdgeFirewallRuleEngineRequest{}
	return &this
}

// GetName returns the Name field value
func (o *EdgeFirewallRuleEngineRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EdgeFirewallRuleEngineRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EdgeFirewallRuleEngineRequest) SetName(v string) {
	o.Name = v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *EdgeFirewallRuleEngineRequest) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EdgeFirewallRuleEngineRequest) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *EdgeFirewallRuleEngineRequest) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *EdgeFirewallRuleEngineRequest) SetActive(v bool) {
	o.Active = &v
}

// GetCriteria returns the Criteria field value
func (o *EdgeFirewallRuleEngineRequest) GetCriteria() [][]EdgeFirewallCriterionFieldRequest {
	if o == nil {
		var ret [][]EdgeFirewallCriterionFieldRequest
		return ret
	}

	return o.Criteria
}

// GetCriteriaOk returns a tuple with the Criteria field value
// and a boolean to check if the value has been set.
func (o *EdgeFirewallRuleEngineRequest) GetCriteriaOk() ([][]EdgeFirewallCriterionFieldRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Criteria, true
}

// SetCriteria sets field value
func (o *EdgeFirewallRuleEngineRequest) SetCriteria(v [][]EdgeFirewallCriterionFieldRequest) {
	o.Criteria = v
}

// GetBehaviors returns the Behaviors field value
func (o *EdgeFirewallRuleEngineRequest) GetBehaviors() []EdgeFirewallBehaviorsRequest {
	if o == nil {
		var ret []EdgeFirewallBehaviorsRequest
		return ret
	}

	return o.Behaviors
}

// GetBehaviorsOk returns a tuple with the Behaviors field value
// and a boolean to check if the value has been set.
func (o *EdgeFirewallRuleEngineRequest) GetBehaviorsOk() ([]EdgeFirewallBehaviorsRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Behaviors, true
}

// SetBehaviors sets field value
func (o *EdgeFirewallRuleEngineRequest) SetBehaviors(v []EdgeFirewallBehaviorsRequest) {
	o.Behaviors = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *EdgeFirewallRuleEngineRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EdgeFirewallRuleEngineRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *EdgeFirewallRuleEngineRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *EdgeFirewallRuleEngineRequest) SetDescription(v string) {
	o.Description = &v
}

func (o EdgeFirewallRuleEngineRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EdgeFirewallRuleEngineRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	toSerialize["criteria"] = o.Criteria
	toSerialize["behaviors"] = o.Behaviors
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *EdgeFirewallRuleEngineRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"criteria",
		"behaviors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEdgeFirewallRuleEngineRequest := _EdgeFirewallRuleEngineRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEdgeFirewallRuleEngineRequest)

	if err != nil {
		return err
	}

	*o = EdgeFirewallRuleEngineRequest(varEdgeFirewallRuleEngineRequest)

	return err
}

type NullableEdgeFirewallRuleEngineRequest struct {
	value *EdgeFirewallRuleEngineRequest
	isSet bool
}

func (v NullableEdgeFirewallRuleEngineRequest) Get() *EdgeFirewallRuleEngineRequest {
	return v.value
}

func (v *NullableEdgeFirewallRuleEngineRequest) Set(val *EdgeFirewallRuleEngineRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEdgeFirewallRuleEngineRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEdgeFirewallRuleEngineRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEdgeFirewallRuleEngineRequest(val *EdgeFirewallRuleEngineRequest) *NullableEdgeFirewallRuleEngineRequest {
	return &NullableEdgeFirewallRuleEngineRequest{value: val, isSet: true}
}

func (v NullableEdgeFirewallRuleEngineRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEdgeFirewallRuleEngineRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


