/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgeapi

import (
	"encoding/json"
	"fmt"
)

// checks if the BehaviorSetConnector type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BehaviorSetConnector{}

// BehaviorSetConnector Set edge connector
type BehaviorSetConnector struct {
	// * `set_connector` - set_connector
	Type string `json:"type"`
	Attributes BehaviorSetConnectorAttributes `json:"attributes"`
	AdditionalProperties map[string]interface{}
}

type _BehaviorSetConnector BehaviorSetConnector

// NewBehaviorSetConnector instantiates a new BehaviorSetConnector object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBehaviorSetConnector(type_ string, attributes BehaviorSetConnectorAttributes) *BehaviorSetConnector {
	this := BehaviorSetConnector{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewBehaviorSetConnectorWithDefaults instantiates a new BehaviorSetConnector object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBehaviorSetConnectorWithDefaults() *BehaviorSetConnector {
	this := BehaviorSetConnector{}
	return &this
}

// GetType returns the Type field value
func (o *BehaviorSetConnector) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BehaviorSetConnector) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BehaviorSetConnector) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *BehaviorSetConnector) GetAttributes() BehaviorSetConnectorAttributes {
	if o == nil {
		var ret BehaviorSetConnectorAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *BehaviorSetConnector) GetAttributesOk() (*BehaviorSetConnectorAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *BehaviorSetConnector) SetAttributes(v BehaviorSetConnectorAttributes) {
	o.Attributes = v
}

func (o BehaviorSetConnector) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BehaviorSetConnector) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BehaviorSetConnector) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBehaviorSetConnector := _BehaviorSetConnector{}

	err = json.Unmarshal(data, &varBehaviorSetConnector)

	if err != nil {
		return err
	}

	*o = BehaviorSetConnector(varBehaviorSetConnector)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "attributes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBehaviorSetConnector struct {
	value *BehaviorSetConnector
	isSet bool
}

func (v NullableBehaviorSetConnector) Get() *BehaviorSetConnector {
	return v.value
}

func (v *NullableBehaviorSetConnector) Set(val *BehaviorSetConnector) {
	v.value = val
	v.isSet = true
}

func (v NullableBehaviorSetConnector) IsSet() bool {
	return v.isSet
}

func (v *NullableBehaviorSetConnector) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBehaviorSetConnector(val *BehaviorSetConnector) *NullableBehaviorSetConnector {
	return &NullableBehaviorSetConnector{value: val, isSet: true}
}

func (v NullableBehaviorSetConnector) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBehaviorSetConnector) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


