/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgeapi

import (
	"encoding/json"
)

// checks if the PaginatedApplicationFunctionInstanceList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedApplicationFunctionInstanceList{}

// PaginatedApplicationFunctionInstanceList struct for PaginatedApplicationFunctionInstanceList
type PaginatedApplicationFunctionInstanceList struct {
	Count *int64 `json:"count,omitempty"`
	Results []ApplicationFunctionInstance `json:"results,omitempty"`
}

// NewPaginatedApplicationFunctionInstanceList instantiates a new PaginatedApplicationFunctionInstanceList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedApplicationFunctionInstanceList() *PaginatedApplicationFunctionInstanceList {
	this := PaginatedApplicationFunctionInstanceList{}
	return &this
}

// NewPaginatedApplicationFunctionInstanceListWithDefaults instantiates a new PaginatedApplicationFunctionInstanceList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedApplicationFunctionInstanceListWithDefaults() *PaginatedApplicationFunctionInstanceList {
	this := PaginatedApplicationFunctionInstanceList{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *PaginatedApplicationFunctionInstanceList) GetCount() int64 {
	if o == nil || IsNil(o.Count) {
		var ret int64
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedApplicationFunctionInstanceList) GetCountOk() (*int64, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *PaginatedApplicationFunctionInstanceList) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int64 and assigns it to the Count field.
func (o *PaginatedApplicationFunctionInstanceList) SetCount(v int64) {
	o.Count = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *PaginatedApplicationFunctionInstanceList) GetResults() []ApplicationFunctionInstance {
	if o == nil || IsNil(o.Results) {
		var ret []ApplicationFunctionInstance
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedApplicationFunctionInstanceList) GetResultsOk() ([]ApplicationFunctionInstance, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *PaginatedApplicationFunctionInstanceList) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []ApplicationFunctionInstance and assigns it to the Results field.
func (o *PaginatedApplicationFunctionInstanceList) SetResults(v []ApplicationFunctionInstance) {
	o.Results = v
}

func (o PaginatedApplicationFunctionInstanceList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedApplicationFunctionInstanceList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullablePaginatedApplicationFunctionInstanceList struct {
	value *PaginatedApplicationFunctionInstanceList
	isSet bool
}

func (v NullablePaginatedApplicationFunctionInstanceList) Get() *PaginatedApplicationFunctionInstanceList {
	return v.value
}

func (v *NullablePaginatedApplicationFunctionInstanceList) Set(val *PaginatedApplicationFunctionInstanceList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedApplicationFunctionInstanceList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedApplicationFunctionInstanceList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedApplicationFunctionInstanceList(val *PaginatedApplicationFunctionInstanceList) *NullablePaginatedApplicationFunctionInstanceList {
	return &NullablePaginatedApplicationFunctionInstanceList{value: val, isSet: true}
}

func (v NullablePaginatedApplicationFunctionInstanceList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedApplicationFunctionInstanceList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


