/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgeapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConnectorHTTPRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectorHTTPRequest{}

// ConnectorHTTPRequest struct for ConnectorHTTPRequest
type ConnectorHTTPRequest struct {
	Name string `json:"name"`
	Active *bool `json:"active,omitempty"`
	// Type of the connector  * `http` - HTTP * `storage` - Storage * `live_ingest` - Live Ingest
	Type string `json:"type"`
	Attributes ConnectorHTTPAttrsReq `json:"attributes"`
}

type _ConnectorHTTPRequest ConnectorHTTPRequest

// NewConnectorHTTPRequest instantiates a new ConnectorHTTPRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorHTTPRequest(name string, type_ string, attributes ConnectorHTTPAttrsReq) *ConnectorHTTPRequest {
	this := ConnectorHTTPRequest{}
	this.Name = name
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewConnectorHTTPRequestWithDefaults instantiates a new ConnectorHTTPRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorHTTPRequestWithDefaults() *ConnectorHTTPRequest {
	this := ConnectorHTTPRequest{}
	return &this
}

// GetName returns the Name field value
func (o *ConnectorHTTPRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ConnectorHTTPRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ConnectorHTTPRequest) SetName(v string) {
	o.Name = v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *ConnectorHTTPRequest) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorHTTPRequest) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *ConnectorHTTPRequest) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *ConnectorHTTPRequest) SetActive(v bool) {
	o.Active = &v
}

// GetType returns the Type field value
func (o *ConnectorHTTPRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ConnectorHTTPRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ConnectorHTTPRequest) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ConnectorHTTPRequest) GetAttributes() ConnectorHTTPAttrsReq {
	if o == nil {
		var ret ConnectorHTTPAttrsReq
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ConnectorHTTPRequest) GetAttributesOk() (*ConnectorHTTPAttrsReq, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ConnectorHTTPRequest) SetAttributes(v ConnectorHTTPAttrsReq) {
	o.Attributes = v
}

func (o ConnectorHTTPRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectorHTTPRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ConnectorHTTPRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectorHTTPRequest := _ConnectorHTTPRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConnectorHTTPRequest)

	if err != nil {
		return err
	}

	*o = ConnectorHTTPRequest(varConnectorHTTPRequest)

	return err
}

type NullableConnectorHTTPRequest struct {
	value *ConnectorHTTPRequest
	isSet bool
}

func (v NullableConnectorHTTPRequest) Get() *ConnectorHTTPRequest {
	return v.value
}

func (v *NullableConnectorHTTPRequest) Set(val *ConnectorHTTPRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorHTTPRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorHTTPRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorHTTPRequest(val *ConnectorHTTPRequest) *NullableConnectorHTTPRequest {
	return &NullableConnectorHTTPRequest{value: val, isSet: true}
}

func (v NullableConnectorHTTPRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorHTTPRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


