/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgeapi

import (
	"encoding/json"
)

// checks if the CacheSettingsModulesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CacheSettingsModulesRequest{}

// CacheSettingsModulesRequest struct for CacheSettingsModulesRequest
type CacheSettingsModulesRequest struct {
	Cache *CacheEdgeRequest `json:"cache,omitempty"`
	ApplicationAccelerator *CacheAccelRequest `json:"application_accelerator,omitempty"`
}

// NewCacheSettingsModulesRequest instantiates a new CacheSettingsModulesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCacheSettingsModulesRequest() *CacheSettingsModulesRequest {
	this := CacheSettingsModulesRequest{}
	return &this
}

// NewCacheSettingsModulesRequestWithDefaults instantiates a new CacheSettingsModulesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheSettingsModulesRequestWithDefaults() *CacheSettingsModulesRequest {
	this := CacheSettingsModulesRequest{}
	return &this
}

// GetCache returns the Cache field value if set, zero value otherwise.
func (o *CacheSettingsModulesRequest) GetCache() CacheEdgeRequest {
	if o == nil || IsNil(o.Cache) {
		var ret CacheEdgeRequest
		return ret
	}
	return *o.Cache
}

// GetCacheOk returns a tuple with the Cache field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheSettingsModulesRequest) GetCacheOk() (*CacheEdgeRequest, bool) {
	if o == nil || IsNil(o.Cache) {
		return nil, false
	}
	return o.Cache, true
}

// HasCache returns a boolean if a field has been set.
func (o *CacheSettingsModulesRequest) HasCache() bool {
	if o != nil && !IsNil(o.Cache) {
		return true
	}

	return false
}

// SetCache gets a reference to the given CacheEdgeRequest and assigns it to the Cache field.
func (o *CacheSettingsModulesRequest) SetCache(v CacheEdgeRequest) {
	o.Cache = &v
}

// GetApplicationAccelerator returns the ApplicationAccelerator field value if set, zero value otherwise.
func (o *CacheSettingsModulesRequest) GetApplicationAccelerator() CacheAccelRequest {
	if o == nil || IsNil(o.ApplicationAccelerator) {
		var ret CacheAccelRequest
		return ret
	}
	return *o.ApplicationAccelerator
}

// GetApplicationAcceleratorOk returns a tuple with the ApplicationAccelerator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheSettingsModulesRequest) GetApplicationAcceleratorOk() (*CacheAccelRequest, bool) {
	if o == nil || IsNil(o.ApplicationAccelerator) {
		return nil, false
	}
	return o.ApplicationAccelerator, true
}

// HasApplicationAccelerator returns a boolean if a field has been set.
func (o *CacheSettingsModulesRequest) HasApplicationAccelerator() bool {
	if o != nil && !IsNil(o.ApplicationAccelerator) {
		return true
	}

	return false
}

// SetApplicationAccelerator gets a reference to the given CacheAccelRequest and assigns it to the ApplicationAccelerator field.
func (o *CacheSettingsModulesRequest) SetApplicationAccelerator(v CacheAccelRequest) {
	o.ApplicationAccelerator = &v
}

func (o CacheSettingsModulesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CacheSettingsModulesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cache) {
		toSerialize["cache"] = o.Cache
	}
	if !IsNil(o.ApplicationAccelerator) {
		toSerialize["application_accelerator"] = o.ApplicationAccelerator
	}
	return toSerialize, nil
}

type NullableCacheSettingsModulesRequest struct {
	value *CacheSettingsModulesRequest
	isSet bool
}

func (v NullableCacheSettingsModulesRequest) Get() *CacheSettingsModulesRequest {
	return v.value
}

func (v *NullableCacheSettingsModulesRequest) Set(val *CacheSettingsModulesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCacheSettingsModulesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCacheSettingsModulesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCacheSettingsModulesRequest(val *CacheSettingsModulesRequest) *NullableCacheSettingsModulesRequest {
	return &NullableCacheSettingsModulesRequest{value: val, isSet: true}
}

func (v NullableCacheSettingsModulesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCacheSettingsModulesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


