/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgeapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// FirewallBehavior - struct for FirewallBehavior
type FirewallBehavior struct {
	FirewallBehaviorNoArgs *FirewallBehaviorNoArgs
	FirewallBehaviorRunFunction *FirewallBehaviorRunFunction
	FirewallBehaviorSetCustomResponse *FirewallBehaviorSetCustomResponse
	FirewallBehaviorSetRateLimit *FirewallBehaviorSetRateLimit
	FirewallBehaviorSetWaf *FirewallBehaviorSetWaf
}

// FirewallBehaviorNoArgsAsFirewallBehavior is a convenience function that returns FirewallBehaviorNoArgs wrapped in FirewallBehavior
func FirewallBehaviorNoArgsAsFirewallBehavior(v *FirewallBehaviorNoArgs) FirewallBehavior {
	return FirewallBehavior{
		FirewallBehaviorNoArgs: v,
	}
}

// FirewallBehaviorRunFunctionAsFirewallBehavior is a convenience function that returns FirewallBehaviorRunFunction wrapped in FirewallBehavior
func FirewallBehaviorRunFunctionAsFirewallBehavior(v *FirewallBehaviorRunFunction) FirewallBehavior {
	return FirewallBehavior{
		FirewallBehaviorRunFunction: v,
	}
}

// FirewallBehaviorSetCustomResponseAsFirewallBehavior is a convenience function that returns FirewallBehaviorSetCustomResponse wrapped in FirewallBehavior
func FirewallBehaviorSetCustomResponseAsFirewallBehavior(v *FirewallBehaviorSetCustomResponse) FirewallBehavior {
	return FirewallBehavior{
		FirewallBehaviorSetCustomResponse: v,
	}
}

// FirewallBehaviorSetRateLimitAsFirewallBehavior is a convenience function that returns FirewallBehaviorSetRateLimit wrapped in FirewallBehavior
func FirewallBehaviorSetRateLimitAsFirewallBehavior(v *FirewallBehaviorSetRateLimit) FirewallBehavior {
	return FirewallBehavior{
		FirewallBehaviorSetRateLimit: v,
	}
}

// FirewallBehaviorSetWafAsFirewallBehavior is a convenience function that returns FirewallBehaviorSetWaf wrapped in FirewallBehavior
func FirewallBehaviorSetWafAsFirewallBehavior(v *FirewallBehaviorSetWaf) FirewallBehavior {
	return FirewallBehavior{
		FirewallBehaviorSetWaf: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *FirewallBehavior) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into FirewallBehaviorNoArgs
	err = newStrictDecoder(data).Decode(&dst.FirewallBehaviorNoArgs)
	if err == nil {
		jsonFirewallBehaviorNoArgs, _ := json.Marshal(dst.FirewallBehaviorNoArgs)
		if string(jsonFirewallBehaviorNoArgs) == "{}" { // empty struct
			dst.FirewallBehaviorNoArgs = nil
		} else {
			if err = validator.Validate(dst.FirewallBehaviorNoArgs); err != nil {
				dst.FirewallBehaviorNoArgs = nil
			} else {
				match++
			}
		}
	} else {
		dst.FirewallBehaviorNoArgs = nil
	}

	// try to unmarshal data into FirewallBehaviorRunFunction
	err = newStrictDecoder(data).Decode(&dst.FirewallBehaviorRunFunction)
	if err == nil {
		jsonFirewallBehaviorRunFunction, _ := json.Marshal(dst.FirewallBehaviorRunFunction)
		if string(jsonFirewallBehaviorRunFunction) == "{}" { // empty struct
			dst.FirewallBehaviorRunFunction = nil
		} else {
			if err = validator.Validate(dst.FirewallBehaviorRunFunction); err != nil {
				dst.FirewallBehaviorRunFunction = nil
			} else {
				match++
			}
		}
	} else {
		dst.FirewallBehaviorRunFunction = nil
	}

	// try to unmarshal data into FirewallBehaviorSetCustomResponse
	err = newStrictDecoder(data).Decode(&dst.FirewallBehaviorSetCustomResponse)
	if err == nil {
		jsonFirewallBehaviorSetCustomResponse, _ := json.Marshal(dst.FirewallBehaviorSetCustomResponse)
		if string(jsonFirewallBehaviorSetCustomResponse) == "{}" { // empty struct
			dst.FirewallBehaviorSetCustomResponse = nil
		} else {
			if err = validator.Validate(dst.FirewallBehaviorSetCustomResponse); err != nil {
				dst.FirewallBehaviorSetCustomResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.FirewallBehaviorSetCustomResponse = nil
	}

	// try to unmarshal data into FirewallBehaviorSetRateLimit
	err = newStrictDecoder(data).Decode(&dst.FirewallBehaviorSetRateLimit)
	if err == nil {
		jsonFirewallBehaviorSetRateLimit, _ := json.Marshal(dst.FirewallBehaviorSetRateLimit)
		if string(jsonFirewallBehaviorSetRateLimit) == "{}" { // empty struct
			dst.FirewallBehaviorSetRateLimit = nil
		} else {
			if err = validator.Validate(dst.FirewallBehaviorSetRateLimit); err != nil {
				dst.FirewallBehaviorSetRateLimit = nil
			} else {
				match++
			}
		}
	} else {
		dst.FirewallBehaviorSetRateLimit = nil
	}

	// try to unmarshal data into FirewallBehaviorSetWaf
	err = newStrictDecoder(data).Decode(&dst.FirewallBehaviorSetWaf)
	if err == nil {
		jsonFirewallBehaviorSetWaf, _ := json.Marshal(dst.FirewallBehaviorSetWaf)
		if string(jsonFirewallBehaviorSetWaf) == "{}" { // empty struct
			dst.FirewallBehaviorSetWaf = nil
		} else {
			if err = validator.Validate(dst.FirewallBehaviorSetWaf); err != nil {
				dst.FirewallBehaviorSetWaf = nil
			} else {
				match++
			}
		}
	} else {
		dst.FirewallBehaviorSetWaf = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.FirewallBehaviorNoArgs = nil
		dst.FirewallBehaviorRunFunction = nil
		dst.FirewallBehaviorSetCustomResponse = nil
		dst.FirewallBehaviorSetRateLimit = nil
		dst.FirewallBehaviorSetWaf = nil

		return fmt.Errorf("data matches more than one schema in oneOf(FirewallBehavior)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(FirewallBehavior)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src FirewallBehavior) MarshalJSON() ([]byte, error) {
	if src.FirewallBehaviorNoArgs != nil {
		return json.Marshal(&src.FirewallBehaviorNoArgs)
	}

	if src.FirewallBehaviorRunFunction != nil {
		return json.Marshal(&src.FirewallBehaviorRunFunction)
	}

	if src.FirewallBehaviorSetCustomResponse != nil {
		return json.Marshal(&src.FirewallBehaviorSetCustomResponse)
	}

	if src.FirewallBehaviorSetRateLimit != nil {
		return json.Marshal(&src.FirewallBehaviorSetRateLimit)
	}

	if src.FirewallBehaviorSetWaf != nil {
		return json.Marshal(&src.FirewallBehaviorSetWaf)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *FirewallBehavior) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.FirewallBehaviorNoArgs != nil {
		return obj.FirewallBehaviorNoArgs
	}

	if obj.FirewallBehaviorRunFunction != nil {
		return obj.FirewallBehaviorRunFunction
	}

	if obj.FirewallBehaviorSetCustomResponse != nil {
		return obj.FirewallBehaviorSetCustomResponse
	}

	if obj.FirewallBehaviorSetRateLimit != nil {
		return obj.FirewallBehaviorSetRateLimit
	}

	if obj.FirewallBehaviorSetWaf != nil {
		return obj.FirewallBehaviorSetWaf
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj FirewallBehavior) GetActualInstanceValue() (interface{}) {
	if obj.FirewallBehaviorNoArgs != nil {
		return *obj.FirewallBehaviorNoArgs
	}

	if obj.FirewallBehaviorRunFunction != nil {
		return *obj.FirewallBehaviorRunFunction
	}

	if obj.FirewallBehaviorSetCustomResponse != nil {
		return *obj.FirewallBehaviorSetCustomResponse
	}

	if obj.FirewallBehaviorSetRateLimit != nil {
		return *obj.FirewallBehaviorSetRateLimit
	}

	if obj.FirewallBehaviorSetWaf != nil {
		return *obj.FirewallBehaviorSetWaf
	}

	// all schemas are nil
	return nil
}

type NullableFirewallBehavior struct {
	value *FirewallBehavior
	isSet bool
}

func (v NullableFirewallBehavior) Get() *FirewallBehavior {
	return v.value
}

func (v *NullableFirewallBehavior) Set(val *FirewallBehavior) {
	v.value = val
	v.isSet = true
}

func (v NullableFirewallBehavior) IsSet() bool {
	return v.isSet
}

func (v *NullableFirewallBehavior) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirewallBehavior(val *FirewallBehavior) *NullableFirewallBehavior {
	return &NullableFirewallBehavior{value: val, isSet: true}
}

func (v NullableFirewallBehavior) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirewallBehavior) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


