/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgeapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest - struct for EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest
type EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest struct {
	EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest *EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest
	EdgeApplicationRequestPhaseBehaviorWithArgsRequest *EdgeApplicationRequestPhaseBehaviorWithArgsRequest
	EdgeApplicationRequestPhaseBehaviorWithoutArgsRequest *EdgeApplicationRequestPhaseBehaviorWithoutArgsRequest
}

// EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequestAsEdgeApplicationRuleEngineRequestPhaseBehaviorsRequest is a convenience function that returns EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest wrapped in EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest
func EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequestAsEdgeApplicationRuleEngineRequestPhaseBehaviorsRequest(v *EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest) EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest {
	return EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest{
		EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest: v,
	}
}

// EdgeApplicationRequestPhaseBehaviorWithArgsRequestAsEdgeApplicationRuleEngineRequestPhaseBehaviorsRequest is a convenience function that returns EdgeApplicationRequestPhaseBehaviorWithArgsRequest wrapped in EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest
func EdgeApplicationRequestPhaseBehaviorWithArgsRequestAsEdgeApplicationRuleEngineRequestPhaseBehaviorsRequest(v *EdgeApplicationRequestPhaseBehaviorWithArgsRequest) EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest {
	return EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest{
		EdgeApplicationRequestPhaseBehaviorWithArgsRequest: v,
	}
}

// EdgeApplicationRequestPhaseBehaviorWithoutArgsRequestAsEdgeApplicationRuleEngineRequestPhaseBehaviorsRequest is a convenience function that returns EdgeApplicationRequestPhaseBehaviorWithoutArgsRequest wrapped in EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest
func EdgeApplicationRequestPhaseBehaviorWithoutArgsRequestAsEdgeApplicationRuleEngineRequestPhaseBehaviorsRequest(v *EdgeApplicationRequestPhaseBehaviorWithoutArgsRequest) EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest {
	return EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest{
		EdgeApplicationRequestPhaseBehaviorWithoutArgsRequest: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest
	err = newStrictDecoder(data).Decode(&dst.EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest)
	if err == nil {
		jsonEdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest, _ := json.Marshal(dst.EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest)
		if string(jsonEdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest) == "{}" { // empty struct
			dst.EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest = nil
		} else {
			if err = validator.Validate(dst.EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest); err != nil {
				dst.EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest = nil
	}

	// try to unmarshal data into EdgeApplicationRequestPhaseBehaviorWithArgsRequest
	err = newStrictDecoder(data).Decode(&dst.EdgeApplicationRequestPhaseBehaviorWithArgsRequest)
	if err == nil {
		jsonEdgeApplicationRequestPhaseBehaviorWithArgsRequest, _ := json.Marshal(dst.EdgeApplicationRequestPhaseBehaviorWithArgsRequest)
		if string(jsonEdgeApplicationRequestPhaseBehaviorWithArgsRequest) == "{}" { // empty struct
			dst.EdgeApplicationRequestPhaseBehaviorWithArgsRequest = nil
		} else {
			if err = validator.Validate(dst.EdgeApplicationRequestPhaseBehaviorWithArgsRequest); err != nil {
				dst.EdgeApplicationRequestPhaseBehaviorWithArgsRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.EdgeApplicationRequestPhaseBehaviorWithArgsRequest = nil
	}

	// try to unmarshal data into EdgeApplicationRequestPhaseBehaviorWithoutArgsRequest
	err = newStrictDecoder(data).Decode(&dst.EdgeApplicationRequestPhaseBehaviorWithoutArgsRequest)
	if err == nil {
		jsonEdgeApplicationRequestPhaseBehaviorWithoutArgsRequest, _ := json.Marshal(dst.EdgeApplicationRequestPhaseBehaviorWithoutArgsRequest)
		if string(jsonEdgeApplicationRequestPhaseBehaviorWithoutArgsRequest) == "{}" { // empty struct
			dst.EdgeApplicationRequestPhaseBehaviorWithoutArgsRequest = nil
		} else {
			if err = validator.Validate(dst.EdgeApplicationRequestPhaseBehaviorWithoutArgsRequest); err != nil {
				dst.EdgeApplicationRequestPhaseBehaviorWithoutArgsRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.EdgeApplicationRequestPhaseBehaviorWithoutArgsRequest = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest = nil
		dst.EdgeApplicationRequestPhaseBehaviorWithArgsRequest = nil
		dst.EdgeApplicationRequestPhaseBehaviorWithoutArgsRequest = nil

		return fmt.Errorf("data matches more than one schema in oneOf(EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest) MarshalJSON() ([]byte, error) {
	if src.EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest != nil {
		return json.Marshal(&src.EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest)
	}

	if src.EdgeApplicationRequestPhaseBehaviorWithArgsRequest != nil {
		return json.Marshal(&src.EdgeApplicationRequestPhaseBehaviorWithArgsRequest)
	}

	if src.EdgeApplicationRequestPhaseBehaviorWithoutArgsRequest != nil {
		return json.Marshal(&src.EdgeApplicationRequestPhaseBehaviorWithoutArgsRequest)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest != nil {
		return obj.EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest
	}

	if obj.EdgeApplicationRequestPhaseBehaviorWithArgsRequest != nil {
		return obj.EdgeApplicationRequestPhaseBehaviorWithArgsRequest
	}

	if obj.EdgeApplicationRequestPhaseBehaviorWithoutArgsRequest != nil {
		return obj.EdgeApplicationRequestPhaseBehaviorWithoutArgsRequest
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest) GetActualInstanceValue() (interface{}) {
	if obj.EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest != nil {
		return *obj.EdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsRequest
	}

	if obj.EdgeApplicationRequestPhaseBehaviorWithArgsRequest != nil {
		return *obj.EdgeApplicationRequestPhaseBehaviorWithArgsRequest
	}

	if obj.EdgeApplicationRequestPhaseBehaviorWithoutArgsRequest != nil {
		return *obj.EdgeApplicationRequestPhaseBehaviorWithoutArgsRequest
	}

	// all schemas are nil
	return nil
}

type NullableEdgeApplicationRuleEngineRequestPhaseBehaviorsRequest struct {
	value *EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest
	isSet bool
}

func (v NullableEdgeApplicationRuleEngineRequestPhaseBehaviorsRequest) Get() *EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest {
	return v.value
}

func (v *NullableEdgeApplicationRuleEngineRequestPhaseBehaviorsRequest) Set(val *EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEdgeApplicationRuleEngineRequestPhaseBehaviorsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEdgeApplicationRuleEngineRequestPhaseBehaviorsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEdgeApplicationRuleEngineRequestPhaseBehaviorsRequest(val *EdgeApplicationRuleEngineRequestPhaseBehaviorsRequest) *NullableEdgeApplicationRuleEngineRequestPhaseBehaviorsRequest {
	return &NullableEdgeApplicationRuleEngineRequestPhaseBehaviorsRequest{value: val, isSet: true}
}

func (v NullableEdgeApplicationRuleEngineRequestPhaseBehaviorsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEdgeApplicationRuleEngineRequestPhaseBehaviorsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


