/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgeapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ApplicationRuleEngineStringAttributesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationRuleEngineStringAttributesRequest{}

// ApplicationRuleEngineStringAttributesRequest struct for ApplicationRuleEngineStringAttributesRequest
type ApplicationRuleEngineStringAttributesRequest struct {
	Value string `json:"value"`
	AdditionalProperties map[string]interface{}
}

type _ApplicationRuleEngineStringAttributesRequest ApplicationRuleEngineStringAttributesRequest

// NewApplicationRuleEngineStringAttributesRequest instantiates a new ApplicationRuleEngineStringAttributesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationRuleEngineStringAttributesRequest(value string) *ApplicationRuleEngineStringAttributesRequest {
	this := ApplicationRuleEngineStringAttributesRequest{}
	this.Value = value
	return &this
}

// NewApplicationRuleEngineStringAttributesRequestWithDefaults instantiates a new ApplicationRuleEngineStringAttributesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationRuleEngineStringAttributesRequestWithDefaults() *ApplicationRuleEngineStringAttributesRequest {
	this := ApplicationRuleEngineStringAttributesRequest{}
	return &this
}

// GetValue returns the Value field value
func (o *ApplicationRuleEngineStringAttributesRequest) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ApplicationRuleEngineStringAttributesRequest) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ApplicationRuleEngineStringAttributesRequest) SetValue(v string) {
	o.Value = v
}

func (o ApplicationRuleEngineStringAttributesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationRuleEngineStringAttributesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApplicationRuleEngineStringAttributesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationRuleEngineStringAttributesRequest := _ApplicationRuleEngineStringAttributesRequest{}

	err = json.Unmarshal(data, &varApplicationRuleEngineStringAttributesRequest)

	if err != nil {
		return err
	}

	*o = ApplicationRuleEngineStringAttributesRequest(varApplicationRuleEngineStringAttributesRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApplicationRuleEngineStringAttributesRequest struct {
	value *ApplicationRuleEngineStringAttributesRequest
	isSet bool
}

func (v NullableApplicationRuleEngineStringAttributesRequest) Get() *ApplicationRuleEngineStringAttributesRequest {
	return v.value
}

func (v *NullableApplicationRuleEngineStringAttributesRequest) Set(val *ApplicationRuleEngineStringAttributesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationRuleEngineStringAttributesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationRuleEngineStringAttributesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationRuleEngineStringAttributesRequest(val *ApplicationRuleEngineStringAttributesRequest) *NullableApplicationRuleEngineStringAttributesRequest {
	return &NullableApplicationRuleEngineStringAttributesRequest{value: val, isSet: true}
}

func (v NullableApplicationRuleEngineStringAttributesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationRuleEngineStringAttributesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


