/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge-api

import (
	"encoding/json"
)

// checks if the ResponseDeleteCustomPages type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseDeleteCustomPages{}

// ResponseDeleteCustomPages struct for ResponseDeleteCustomPages
type ResponseDeleteCustomPages struct {
	State *string `json:"state,omitempty" validate:"regexp=.*"`
}

// NewResponseDeleteCustomPages instantiates a new ResponseDeleteCustomPages object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseDeleteCustomPages() *ResponseDeleteCustomPages {
	this := ResponseDeleteCustomPages{}
	return &this
}

// NewResponseDeleteCustomPagesWithDefaults instantiates a new ResponseDeleteCustomPages object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseDeleteCustomPagesWithDefaults() *ResponseDeleteCustomPages {
	this := ResponseDeleteCustomPages{}
	return &this
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ResponseDeleteCustomPages) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseDeleteCustomPages) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ResponseDeleteCustomPages) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *ResponseDeleteCustomPages) SetState(v string) {
	o.State = &v
}

func (o ResponseDeleteCustomPages) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseDeleteCustomPages) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

type NullableResponseDeleteCustomPages struct {
	value *ResponseDeleteCustomPages
	isSet bool
}

func (v NullableResponseDeleteCustomPages) Get() *ResponseDeleteCustomPages {
	return v.value
}

func (v *NullableResponseDeleteCustomPages) Set(val *ResponseDeleteCustomPages) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseDeleteCustomPages) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseDeleteCustomPages) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseDeleteCustomPages(val *ResponseDeleteCustomPages) *NullableResponseDeleteCustomPages {
	return &NullableResponseDeleteCustomPages{value: val, isSet: true}
}

func (v NullableResponseDeleteCustomPages) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseDeleteCustomPages) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


