/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgeapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AppRuleRunFunction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppRuleRunFunction{}

// AppRuleRunFunction Run a function
type AppRuleRunFunction struct {
	// * `run_function` - run_function
	Type string `json:"type"`
	Attributes AppRuleRunFunctionAttrs `json:"attributes"`
	AdditionalProperties map[string]interface{}
}

type _AppRuleRunFunction AppRuleRunFunction

// NewAppRuleRunFunction instantiates a new AppRuleRunFunction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppRuleRunFunction(type_ string, attributes AppRuleRunFunctionAttrs) *AppRuleRunFunction {
	this := AppRuleRunFunction{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewAppRuleRunFunctionWithDefaults instantiates a new AppRuleRunFunction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppRuleRunFunctionWithDefaults() *AppRuleRunFunction {
	this := AppRuleRunFunction{}
	return &this
}

// GetType returns the Type field value
func (o *AppRuleRunFunction) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AppRuleRunFunction) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AppRuleRunFunction) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *AppRuleRunFunction) GetAttributes() AppRuleRunFunctionAttrs {
	if o == nil {
		var ret AppRuleRunFunctionAttrs
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *AppRuleRunFunction) GetAttributesOk() (*AppRuleRunFunctionAttrs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *AppRuleRunFunction) SetAttributes(v AppRuleRunFunctionAttrs) {
	o.Attributes = v
}

func (o AppRuleRunFunction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppRuleRunFunction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AppRuleRunFunction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppRuleRunFunction := _AppRuleRunFunction{}

	err = json.Unmarshal(data, &varAppRuleRunFunction)

	if err != nil {
		return err
	}

	*o = AppRuleRunFunction(varAppRuleRunFunction)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "attributes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAppRuleRunFunction struct {
	value *AppRuleRunFunction
	isSet bool
}

func (v NullableAppRuleRunFunction) Get() *AppRuleRunFunction {
	return v.value
}

func (v *NullableAppRuleRunFunction) Set(val *AppRuleRunFunction) {
	v.value = val
	v.isSet = true
}

func (v NullableAppRuleRunFunction) IsSet() bool {
	return v.isSet
}

func (v *NullableAppRuleRunFunction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppRuleRunFunction(val *AppRuleRunFunction) *NullableAppRuleRunFunction {
	return &NullableAppRuleRunFunction{value: val, isSet: true}
}

func (v NullableAppRuleRunFunction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppRuleRunFunction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


