/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgeapi

import (
	"encoding/json"
	"fmt"
)

// checks if the FwBehaviorWaf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FwBehaviorWaf{}

// FwBehaviorWaf Set a WAF
type FwBehaviorWaf struct {
	// * `set_waf` - set_waf
	Type string `json:"type"`
	Attributes FwBehaviorWAttrs `json:"attributes"`
	AdditionalProperties map[string]interface{}
}

type _FwBehaviorWaf FwBehaviorWaf

// NewFwBehaviorWaf instantiates a new FwBehaviorWaf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFwBehaviorWaf(type_ string, attributes FwBehaviorWAttrs) *FwBehaviorWaf {
	this := FwBehaviorWaf{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewFwBehaviorWafWithDefaults instantiates a new FwBehaviorWaf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFwBehaviorWafWithDefaults() *FwBehaviorWaf {
	this := FwBehaviorWaf{}
	return &this
}

// GetType returns the Type field value
func (o *FwBehaviorWaf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *FwBehaviorWaf) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *FwBehaviorWaf) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *FwBehaviorWaf) GetAttributes() FwBehaviorWAttrs {
	if o == nil {
		var ret FwBehaviorWAttrs
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *FwBehaviorWaf) GetAttributesOk() (*FwBehaviorWAttrs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *FwBehaviorWaf) SetAttributes(v FwBehaviorWAttrs) {
	o.Attributes = v
}

func (o FwBehaviorWaf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FwBehaviorWaf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FwBehaviorWaf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFwBehaviorWaf := _FwBehaviorWaf{}

	err = json.Unmarshal(data, &varFwBehaviorWaf)

	if err != nil {
		return err
	}

	*o = FwBehaviorWaf(varFwBehaviorWaf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "attributes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFwBehaviorWaf struct {
	value *FwBehaviorWaf
	isSet bool
}

func (v NullableFwBehaviorWaf) Get() *FwBehaviorWaf {
	return v.value
}

func (v *NullableFwBehaviorWaf) Set(val *FwBehaviorWaf) {
	v.value = val
	v.isSet = true
}

func (v NullableFwBehaviorWaf) IsSet() bool {
	return v.isSet
}

func (v *NullableFwBehaviorWaf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFwBehaviorWaf(val *FwBehaviorWaf) *NullableFwBehaviorWaf {
	return &NullableFwBehaviorWaf{value: val, isSet: true}
}

func (v NullableFwBehaviorWaf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFwBehaviorWaf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


