/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge-api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EdgeFirewallBehaviorRunFunctionAttributesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EdgeFirewallBehaviorRunFunctionAttributesRequest{}

// EdgeFirewallBehaviorRunFunctionAttributesRequest struct for EdgeFirewallBehaviorRunFunctionAttributesRequest
type EdgeFirewallBehaviorRunFunctionAttributesRequest struct {
	Value int64 `json:"value"`
}

type _EdgeFirewallBehaviorRunFunctionAttributesRequest EdgeFirewallBehaviorRunFunctionAttributesRequest

// NewEdgeFirewallBehaviorRunFunctionAttributesRequest instantiates a new EdgeFirewallBehaviorRunFunctionAttributesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEdgeFirewallBehaviorRunFunctionAttributesRequest(value int64) *EdgeFirewallBehaviorRunFunctionAttributesRequest {
	this := EdgeFirewallBehaviorRunFunctionAttributesRequest{}
	this.Value = value
	return &this
}

// NewEdgeFirewallBehaviorRunFunctionAttributesRequestWithDefaults instantiates a new EdgeFirewallBehaviorRunFunctionAttributesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEdgeFirewallBehaviorRunFunctionAttributesRequestWithDefaults() *EdgeFirewallBehaviorRunFunctionAttributesRequest {
	this := EdgeFirewallBehaviorRunFunctionAttributesRequest{}
	return &this
}

// GetValue returns the Value field value
func (o *EdgeFirewallBehaviorRunFunctionAttributesRequest) GetValue() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *EdgeFirewallBehaviorRunFunctionAttributesRequest) GetValueOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *EdgeFirewallBehaviorRunFunctionAttributesRequest) SetValue(v int64) {
	o.Value = v
}

func (o EdgeFirewallBehaviorRunFunctionAttributesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EdgeFirewallBehaviorRunFunctionAttributesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *EdgeFirewallBehaviorRunFunctionAttributesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEdgeFirewallBehaviorRunFunctionAttributesRequest := _EdgeFirewallBehaviorRunFunctionAttributesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEdgeFirewallBehaviorRunFunctionAttributesRequest)

	if err != nil {
		return err
	}

	*o = EdgeFirewallBehaviorRunFunctionAttributesRequest(varEdgeFirewallBehaviorRunFunctionAttributesRequest)

	return err
}

type NullableEdgeFirewallBehaviorRunFunctionAttributesRequest struct {
	value *EdgeFirewallBehaviorRunFunctionAttributesRequest
	isSet bool
}

func (v NullableEdgeFirewallBehaviorRunFunctionAttributesRequest) Get() *EdgeFirewallBehaviorRunFunctionAttributesRequest {
	return v.value
}

func (v *NullableEdgeFirewallBehaviorRunFunctionAttributesRequest) Set(val *EdgeFirewallBehaviorRunFunctionAttributesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEdgeFirewallBehaviorRunFunctionAttributesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEdgeFirewallBehaviorRunFunctionAttributesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEdgeFirewallBehaviorRunFunctionAttributesRequest(val *EdgeFirewallBehaviorRunFunctionAttributesRequest) *NullableEdgeFirewallBehaviorRunFunctionAttributesRequest {
	return &NullableEdgeFirewallBehaviorRunFunctionAttributesRequest{value: val, isSet: true}
}

func (v NullableEdgeFirewallBehaviorRunFunctionAttributesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEdgeFirewallBehaviorRunFunctionAttributesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


