/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgeapi

import (
	"encoding/json"
)

// checks if the ResponseDeleteCacheSetting type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseDeleteCacheSetting{}

// ResponseDeleteCacheSetting struct for ResponseDeleteCacheSetting
type ResponseDeleteCacheSetting struct {
	State *string `json:"state,omitempty"`
}

// NewResponseDeleteCacheSetting instantiates a new ResponseDeleteCacheSetting object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseDeleteCacheSetting() *ResponseDeleteCacheSetting {
	this := ResponseDeleteCacheSetting{}
	return &this
}

// NewResponseDeleteCacheSettingWithDefaults instantiates a new ResponseDeleteCacheSetting object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseDeleteCacheSettingWithDefaults() *ResponseDeleteCacheSetting {
	this := ResponseDeleteCacheSetting{}
	return &this
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ResponseDeleteCacheSetting) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseDeleteCacheSetting) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ResponseDeleteCacheSetting) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *ResponseDeleteCacheSetting) SetState(v string) {
	o.State = &v
}

func (o ResponseDeleteCacheSetting) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseDeleteCacheSetting) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

type NullableResponseDeleteCacheSetting struct {
	value *ResponseDeleteCacheSetting
	isSet bool
}

func (v NullableResponseDeleteCacheSetting) Get() *ResponseDeleteCacheSetting {
	return v.value
}

func (v *NullableResponseDeleteCacheSetting) Set(val *ResponseDeleteCacheSetting) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseDeleteCacheSetting) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseDeleteCacheSetting) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseDeleteCacheSetting(val *ResponseDeleteCacheSetting) *NullableResponseDeleteCacheSetting {
	return &NullableResponseDeleteCacheSetting{value: val, isSet: true}
}

func (v NullableResponseDeleteCacheSetting) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseDeleteCacheSetting) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


