/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgeapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResponseBehaviorFilterHeaderAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseBehaviorFilterHeaderAttributes{}

// ResponseBehaviorFilterHeaderAttributes struct for ResponseBehaviorFilterHeaderAttributes
type ResponseBehaviorFilterHeaderAttributes struct {
	Value string `json:"value"`
}

type _ResponseBehaviorFilterHeaderAttributes ResponseBehaviorFilterHeaderAttributes

// NewResponseBehaviorFilterHeaderAttributes instantiates a new ResponseBehaviorFilterHeaderAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseBehaviorFilterHeaderAttributes(value string) *ResponseBehaviorFilterHeaderAttributes {
	this := ResponseBehaviorFilterHeaderAttributes{}
	this.Value = value
	return &this
}

// NewResponseBehaviorFilterHeaderAttributesWithDefaults instantiates a new ResponseBehaviorFilterHeaderAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseBehaviorFilterHeaderAttributesWithDefaults() *ResponseBehaviorFilterHeaderAttributes {
	this := ResponseBehaviorFilterHeaderAttributes{}
	return &this
}

// GetValue returns the Value field value
func (o *ResponseBehaviorFilterHeaderAttributes) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ResponseBehaviorFilterHeaderAttributes) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ResponseBehaviorFilterHeaderAttributes) SetValue(v string) {
	o.Value = v
}

func (o ResponseBehaviorFilterHeaderAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseBehaviorFilterHeaderAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *ResponseBehaviorFilterHeaderAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseBehaviorFilterHeaderAttributes := _ResponseBehaviorFilterHeaderAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponseBehaviorFilterHeaderAttributes)

	if err != nil {
		return err
	}

	*o = ResponseBehaviorFilterHeaderAttributes(varResponseBehaviorFilterHeaderAttributes)

	return err
}

type NullableResponseBehaviorFilterHeaderAttributes struct {
	value *ResponseBehaviorFilterHeaderAttributes
	isSet bool
}

func (v NullableResponseBehaviorFilterHeaderAttributes) Get() *ResponseBehaviorFilterHeaderAttributes {
	return v.value
}

func (v *NullableResponseBehaviorFilterHeaderAttributes) Set(val *ResponseBehaviorFilterHeaderAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseBehaviorFilterHeaderAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseBehaviorFilterHeaderAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseBehaviorFilterHeaderAttributes(val *ResponseBehaviorFilterHeaderAttributes) *NullableResponseBehaviorFilterHeaderAttributes {
	return &NullableResponseBehaviorFilterHeaderAttributes{value: val, isSet: true}
}

func (v NullableResponseBehaviorFilterHeaderAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseBehaviorFilterHeaderAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


