/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgeapi

import (
	"encoding/json"
)

// checks if the PatchedFirewallFunctionInstanRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedFirewallFunctionInstanRequest{}

// PatchedFirewallFunctionInstanRequest Serializer for Firewall Function Instances
type PatchedFirewallFunctionInstanRequest struct {
	Name *string `json:"name,omitempty"`
	Args interface{} `json:"args,omitempty"`
	AzionForm *EdgeFunctionsAzionForm `json:"azion_form,omitempty"`
	Function *int64 `json:"function,omitempty"`
	Active *bool `json:"active,omitempty"`
}

// NewPatchedFirewallFunctionInstanRequest instantiates a new PatchedFirewallFunctionInstanRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedFirewallFunctionInstanRequest() *PatchedFirewallFunctionInstanRequest {
	this := PatchedFirewallFunctionInstanRequest{}
	return &this
}

// NewPatchedFirewallFunctionInstanRequestWithDefaults instantiates a new PatchedFirewallFunctionInstanRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedFirewallFunctionInstanRequestWithDefaults() *PatchedFirewallFunctionInstanRequest {
	this := PatchedFirewallFunctionInstanRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchedFirewallFunctionInstanRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedFirewallFunctionInstanRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchedFirewallFunctionInstanRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchedFirewallFunctionInstanRequest) SetName(v string) {
	o.Name = &v
}

// GetArgs returns the Args field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedFirewallFunctionInstanRequest) GetArgs() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Args
}

// GetArgsOk returns a tuple with the Args field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedFirewallFunctionInstanRequest) GetArgsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Args) {
		return nil, false
	}
	return &o.Args, true
}

// HasArgs returns a boolean if a field has been set.
func (o *PatchedFirewallFunctionInstanRequest) HasArgs() bool {
	if o != nil && !IsNil(o.Args) {
		return true
	}

	return false
}

// SetArgs gets a reference to the given interface{} and assigns it to the Args field.
func (o *PatchedFirewallFunctionInstanRequest) SetArgs(v interface{}) {
	o.Args = v
}

// GetAzionForm returns the AzionForm field value if set, zero value otherwise.
func (o *PatchedFirewallFunctionInstanRequest) GetAzionForm() EdgeFunctionsAzionForm {
	if o == nil || IsNil(o.AzionForm) {
		var ret EdgeFunctionsAzionForm
		return ret
	}
	return *o.AzionForm
}

// GetAzionFormOk returns a tuple with the AzionForm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedFirewallFunctionInstanRequest) GetAzionFormOk() (*EdgeFunctionsAzionForm, bool) {
	if o == nil || IsNil(o.AzionForm) {
		return nil, false
	}
	return o.AzionForm, true
}

// HasAzionForm returns a boolean if a field has been set.
func (o *PatchedFirewallFunctionInstanRequest) HasAzionForm() bool {
	if o != nil && !IsNil(o.AzionForm) {
		return true
	}

	return false
}

// SetAzionForm gets a reference to the given EdgeFunctionsAzionForm and assigns it to the AzionForm field.
func (o *PatchedFirewallFunctionInstanRequest) SetAzionForm(v EdgeFunctionsAzionForm) {
	o.AzionForm = &v
}

// GetFunction returns the Function field value if set, zero value otherwise.
func (o *PatchedFirewallFunctionInstanRequest) GetFunction() int64 {
	if o == nil || IsNil(o.Function) {
		var ret int64
		return ret
	}
	return *o.Function
}

// GetFunctionOk returns a tuple with the Function field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedFirewallFunctionInstanRequest) GetFunctionOk() (*int64, bool) {
	if o == nil || IsNil(o.Function) {
		return nil, false
	}
	return o.Function, true
}

// HasFunction returns a boolean if a field has been set.
func (o *PatchedFirewallFunctionInstanRequest) HasFunction() bool {
	if o != nil && !IsNil(o.Function) {
		return true
	}

	return false
}

// SetFunction gets a reference to the given int64 and assigns it to the Function field.
func (o *PatchedFirewallFunctionInstanRequest) SetFunction(v int64) {
	o.Function = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *PatchedFirewallFunctionInstanRequest) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedFirewallFunctionInstanRequest) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *PatchedFirewallFunctionInstanRequest) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *PatchedFirewallFunctionInstanRequest) SetActive(v bool) {
	o.Active = &v
}

func (o PatchedFirewallFunctionInstanRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedFirewallFunctionInstanRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Args != nil {
		toSerialize["args"] = o.Args
	}
	if !IsNil(o.AzionForm) {
		toSerialize["azion_form"] = o.AzionForm
	}
	if !IsNil(o.Function) {
		toSerialize["function"] = o.Function
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	return toSerialize, nil
}

type NullablePatchedFirewallFunctionInstanRequest struct {
	value *PatchedFirewallFunctionInstanRequest
	isSet bool
}

func (v NullablePatchedFirewallFunctionInstanRequest) Get() *PatchedFirewallFunctionInstanRequest {
	return v.value
}

func (v *NullablePatchedFirewallFunctionInstanRequest) Set(val *PatchedFirewallFunctionInstanRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedFirewallFunctionInstanRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedFirewallFunctionInstanRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedFirewallFunctionInstanRequest(val *PatchedFirewallFunctionInstanRequest) *NullablePatchedFirewallFunctionInstanRequest {
	return &NullablePatchedFirewallFunctionInstanRequest{value: val, isSet: true}
}

func (v NullablePatchedFirewallFunctionInstanRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedFirewallFunctionInstanRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


