/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgeapi

import (
	"encoding/json"
	"fmt"
)

// checks if the EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups{}

// EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups struct for EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups
type EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups struct {
	// * `capture_match_groups` - capture_match_groups
	Type string `json:"type"`
	Attributes EdgeApplicationRuleEngineCaptureMatchGroupsAttributesRequest `json:"attributes"`
	AdditionalProperties map[string]interface{}
}

type _EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups

// NewEdgeApplicationRequestPhaseBehaviorCaptureMatchGroups instantiates a new EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEdgeApplicationRequestPhaseBehaviorCaptureMatchGroups(type_ string, attributes EdgeApplicationRuleEngineCaptureMatchGroupsAttributesRequest) *EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups {
	this := EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewEdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsWithDefaults instantiates a new EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEdgeApplicationRequestPhaseBehaviorCaptureMatchGroupsWithDefaults() *EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups {
	this := EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups{}
	return &this
}

// GetType returns the Type field value
func (o *EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups) GetAttributes() EdgeApplicationRuleEngineCaptureMatchGroupsAttributesRequest {
	if o == nil {
		var ret EdgeApplicationRuleEngineCaptureMatchGroupsAttributesRequest
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups) GetAttributesOk() (*EdgeApplicationRuleEngineCaptureMatchGroupsAttributesRequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups) SetAttributes(v EdgeApplicationRuleEngineCaptureMatchGroupsAttributesRequest) {
	o.Attributes = v
}

func (o EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEdgeApplicationRequestPhaseBehaviorCaptureMatchGroups := _EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups{}

	err = json.Unmarshal(data, &varEdgeApplicationRequestPhaseBehaviorCaptureMatchGroups)

	if err != nil {
		return err
	}

	*o = EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups(varEdgeApplicationRequestPhaseBehaviorCaptureMatchGroups)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "attributes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEdgeApplicationRequestPhaseBehaviorCaptureMatchGroups struct {
	value *EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups
	isSet bool
}

func (v NullableEdgeApplicationRequestPhaseBehaviorCaptureMatchGroups) Get() *EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups {
	return v.value
}

func (v *NullableEdgeApplicationRequestPhaseBehaviorCaptureMatchGroups) Set(val *EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups) {
	v.value = val
	v.isSet = true
}

func (v NullableEdgeApplicationRequestPhaseBehaviorCaptureMatchGroups) IsSet() bool {
	return v.isSet
}

func (v *NullableEdgeApplicationRequestPhaseBehaviorCaptureMatchGroups) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEdgeApplicationRequestPhaseBehaviorCaptureMatchGroups(val *EdgeApplicationRequestPhaseBehaviorCaptureMatchGroups) *NullableEdgeApplicationRequestPhaseBehaviorCaptureMatchGroups {
	return &NullableEdgeApplicationRequestPhaseBehaviorCaptureMatchGroups{value: val, isSet: true}
}

func (v NullableEdgeApplicationRequestPhaseBehaviorCaptureMatchGroups) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEdgeApplicationRequestPhaseBehaviorCaptureMatchGroups) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


