/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edge-api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EdgeConnectorLiveIngestTypeProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EdgeConnectorLiveIngestTypeProperties{}

// EdgeConnectorLiveIngestTypeProperties struct for EdgeConnectorLiveIngestTypeProperties
type EdgeConnectorLiveIngestTypeProperties struct {
	Endpoint string `json:"endpoint" validate:"regexp=.*"`
}

type _EdgeConnectorLiveIngestTypeProperties EdgeConnectorLiveIngestTypeProperties

// NewEdgeConnectorLiveIngestTypeProperties instantiates a new EdgeConnectorLiveIngestTypeProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEdgeConnectorLiveIngestTypeProperties(endpoint string) *EdgeConnectorLiveIngestTypeProperties {
	this := EdgeConnectorLiveIngestTypeProperties{}
	this.Endpoint = endpoint
	return &this
}

// NewEdgeConnectorLiveIngestTypePropertiesWithDefaults instantiates a new EdgeConnectorLiveIngestTypeProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEdgeConnectorLiveIngestTypePropertiesWithDefaults() *EdgeConnectorLiveIngestTypeProperties {
	this := EdgeConnectorLiveIngestTypeProperties{}
	return &this
}

// GetEndpoint returns the Endpoint field value
func (o *EdgeConnectorLiveIngestTypeProperties) GetEndpoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value
// and a boolean to check if the value has been set.
func (o *EdgeConnectorLiveIngestTypeProperties) GetEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Endpoint, true
}

// SetEndpoint sets field value
func (o *EdgeConnectorLiveIngestTypeProperties) SetEndpoint(v string) {
	o.Endpoint = v
}

func (o EdgeConnectorLiveIngestTypeProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EdgeConnectorLiveIngestTypeProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["endpoint"] = o.Endpoint
	return toSerialize, nil
}

func (o *EdgeConnectorLiveIngestTypeProperties) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"endpoint",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEdgeConnectorLiveIngestTypeProperties := _EdgeConnectorLiveIngestTypeProperties{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEdgeConnectorLiveIngestTypeProperties)

	if err != nil {
		return err
	}

	*o = EdgeConnectorLiveIngestTypeProperties(varEdgeConnectorLiveIngestTypeProperties)

	return err
}

type NullableEdgeConnectorLiveIngestTypeProperties struct {
	value *EdgeConnectorLiveIngestTypeProperties
	isSet bool
}

func (v NullableEdgeConnectorLiveIngestTypeProperties) Get() *EdgeConnectorLiveIngestTypeProperties {
	return v.value
}

func (v *NullableEdgeConnectorLiveIngestTypeProperties) Set(val *EdgeConnectorLiveIngestTypeProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableEdgeConnectorLiveIngestTypeProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableEdgeConnectorLiveIngestTypeProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEdgeConnectorLiveIngestTypeProperties(val *EdgeConnectorLiveIngestTypeProperties) *NullableEdgeConnectorLiveIngestTypeProperties {
	return &NullableEdgeConnectorLiveIngestTypeProperties{value: val, isSet: true}
}

func (v NullableEdgeConnectorLiveIngestTypeProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEdgeConnectorLiveIngestTypeProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


