/*
edge-api

REST API OpenAPI documentation for the edge-api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgeapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ConnectorPolymorphicConnectorHTTPRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectorPolymorphicConnectorHTTPRequest{}

// ConnectorPolymorphicConnectorHTTPRequest struct for ConnectorPolymorphicConnectorHTTPRequest
type ConnectorPolymorphicConnectorHTTPRequest struct {
	// Type of the connector  * `http` - HTTP * `storage` - Storage * `live_ingest` - Live Ingest
	Type string `json:"type"`
	Name string `json:"name"`
	Active *bool `json:"active,omitempty"`
	Attributes ConnectorHTTPAttributesRequest `json:"attributes"`
	AdditionalProperties map[string]interface{}
}

type _ConnectorPolymorphicConnectorHTTPRequest ConnectorPolymorphicConnectorHTTPRequest

// NewConnectorPolymorphicConnectorHTTPRequest instantiates a new ConnectorPolymorphicConnectorHTTPRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorPolymorphicConnectorHTTPRequest(type_ string, name string, attributes ConnectorHTTPAttributesRequest) *ConnectorPolymorphicConnectorHTTPRequest {
	this := ConnectorPolymorphicConnectorHTTPRequest{}
	this.Type = type_
	this.Name = name
	this.Attributes = attributes
	return &this
}

// NewConnectorPolymorphicConnectorHTTPRequestWithDefaults instantiates a new ConnectorPolymorphicConnectorHTTPRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorPolymorphicConnectorHTTPRequestWithDefaults() *ConnectorPolymorphicConnectorHTTPRequest {
	this := ConnectorPolymorphicConnectorHTTPRequest{}
	return &this
}

// GetType returns the Type field value
func (o *ConnectorPolymorphicConnectorHTTPRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ConnectorPolymorphicConnectorHTTPRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ConnectorPolymorphicConnectorHTTPRequest) SetType(v string) {
	o.Type = v
}

// GetName returns the Name field value
func (o *ConnectorPolymorphicConnectorHTTPRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ConnectorPolymorphicConnectorHTTPRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ConnectorPolymorphicConnectorHTTPRequest) SetName(v string) {
	o.Name = v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *ConnectorPolymorphicConnectorHTTPRequest) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorPolymorphicConnectorHTTPRequest) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *ConnectorPolymorphicConnectorHTTPRequest) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *ConnectorPolymorphicConnectorHTTPRequest) SetActive(v bool) {
	o.Active = &v
}

// GetAttributes returns the Attributes field value
func (o *ConnectorPolymorphicConnectorHTTPRequest) GetAttributes() ConnectorHTTPAttributesRequest {
	if o == nil {
		var ret ConnectorHTTPAttributesRequest
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ConnectorPolymorphicConnectorHTTPRequest) GetAttributesOk() (*ConnectorHTTPAttributesRequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ConnectorPolymorphicConnectorHTTPRequest) SetAttributes(v ConnectorHTTPAttributesRequest) {
	o.Attributes = v
}

func (o ConnectorPolymorphicConnectorHTTPRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectorPolymorphicConnectorHTTPRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	toSerialize["attributes"] = o.Attributes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConnectorPolymorphicConnectorHTTPRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"name",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectorPolymorphicConnectorHTTPRequest := _ConnectorPolymorphicConnectorHTTPRequest{}

	err = json.Unmarshal(data, &varConnectorPolymorphicConnectorHTTPRequest)

	if err != nil {
		return err
	}

	*o = ConnectorPolymorphicConnectorHTTPRequest(varConnectorPolymorphicConnectorHTTPRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "name")
		delete(additionalProperties, "active")
		delete(additionalProperties, "attributes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConnectorPolymorphicConnectorHTTPRequest struct {
	value *ConnectorPolymorphicConnectorHTTPRequest
	isSet bool
}

func (v NullableConnectorPolymorphicConnectorHTTPRequest) Get() *ConnectorPolymorphicConnectorHTTPRequest {
	return v.value
}

func (v *NullableConnectorPolymorphicConnectorHTTPRequest) Set(val *ConnectorPolymorphicConnectorHTTPRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorPolymorphicConnectorHTTPRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorPolymorphicConnectorHTTPRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorPolymorphicConnectorHTTPRequest(val *ConnectorPolymorphicConnectorHTTPRequest) *NullableConnectorPolymorphicConnectorHTTPRequest {
	return &NullableConnectorPolymorphicConnectorHTTPRequest{value: val, isSet: true}
}

func (v NullableConnectorPolymorphicConnectorHTTPRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorPolymorphicConnectorHTTPRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


